import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, AlertTriangle, Check, Database, Gauge, RefreshCw, ShieldCheck, User, X } from 'lucide-react';
import { api } from '../../lib/api';

type ApprovalItem = { key: string; type: 'sql' | 'transfer'; row: any; requestedAt: string };

export function DatabaseApprovalsPage() {
  const qc = useQueryClient();
  const [selectedKey, setSelectedKey] = useState('');
  const approvals = useQuery<any[]>({ queryKey: ['database-approvals'], queryFn: async () => (await api.get('/db-query/approvals/admin', { params: { pageSize: 200 } })).data.items, refetchInterval: 5000 });
  const transfers = useQuery<any[]>({ queryKey: ['database-transfers-admin'], queryFn: async () => (await api.get('/db-query/transfers/admin', { params: { pageSize: 200 } })).data.items, refetchInterval: 5000 });
  const items = useMemo<ApprovalItem[]>(() => [
    ...(approvals.data || []).map((row) => ({ key: `sql:${row.id}`, type: 'sql' as const, row, requestedAt: row.requestedAt })),
    ...(transfers.data || []).map((row) => ({ key: `transfer:${row.id}`, type: 'transfer' as const, row, requestedAt: row.requestedAt })),
  ].sort((a, b) => +new Date(b.requestedAt) - +new Date(a.requestedAt)), [approvals.data, transfers.data]);
  useEffect(() => { if (!selectedKey && items[0]) setSelectedKey(items[0].key); if (selectedKey && !items.some((item) => item.key === selectedKey)) setSelectedKey(items[0]?.key || ''); }, [items, selectedKey]);
  const selected = items.find((item) => item.key === selectedKey);
  const refresh = () => { qc.invalidateQueries({ queryKey: ['database-approvals'] }); qc.invalidateQueries({ queryKey: ['database-transfers-admin'] }); };
  const action = useMutation({ mutationFn: ({ url, reason }: { url: string; reason?: string }) => api.post(url, reason ? { reason } : {}), onSuccess: refresh });
  const decide = (approve: boolean) => { if (!selected) return; const base = selected.type === 'sql' ? `/db-query/approvals/${selected.row.id}` : `/db-query/transfers/${selected.row.id}`; if (approve) action.mutate({ url: `${base}/approve` }); else { const reason = window.prompt('请输入拒绝原因'); if (reason?.trim()) action.mutate({ url: `${base}/reject`, reason }); } };
  const loading = approvals.isLoading || transfers.isLoading;
  return <div className="flex h-[calc(100vh-7rem)] min-h-[520px] flex-col"><header className="mb-4 flex items-end justify-between"><div><div className="eyebrow">Datasource Approval</div><h1 className="mt-1 text-2xl font-bold">数据库审批</h1><p className="mt-1 text-sm text-muted">点击申请查看详情、SQL 执行计划和审批人</p></div><button className="btn btn-secondary" onClick={() => { approvals.refetch(); transfers.refetch(); }}><RefreshCw size={14} />刷新</button></header>
    <div className="grid min-h-0 flex-1 overflow-hidden rounded-2xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950 lg:grid-cols-[360px_minmax(0,1fr)]"><aside className="min-h-0 overflow-y-auto border-r dark:border-slate-800"><div className="sticky top-0 z-10 border-b bg-slate-50/95 px-4 py-3 text-xs font-semibold text-muted backdrop-blur dark:border-slate-800 dark:bg-slate-900/95">申请列表 · {items.length}</div>{loading && <p className="p-6 text-center text-xs text-muted">加载中…</p>}{!loading && !items.length && <p className="p-10 text-center text-xs text-muted">暂无需要你处理的申请</p>}{items.map((item) => <ApprovalListRow key={item.key} item={item} active={item.key === selectedKey} onClick={() => setSelectedKey(item.key)} />)}</aside>
      <main className="min-h-0 overflow-y-auto">{selected ? <ApprovalDetail item={selected} pending={action.isPending} onApprove={() => decide(true)} onReject={() => decide(false)} /> : <div className="grid h-full place-items-center text-sm text-muted">从列表选择一条申请</div>}</main></div>
  </div>;
}

function ApprovalListRow({ item, active, onClick }: { item: ApprovalItem; active: boolean; onClick: () => void }) {
  const row = item.row; const pending = row.status === 'pending' || row.status === 'pending_approval';
  const title = item.type === 'sql' ? `${row.operation.toUpperCase()} · ${row.datasource.name}` : `${transferLabel(row.kind)} · ${row.sourceDatasource.name}`;
  return <button onClick={onClick} className={`block w-full border-b px-4 py-3 text-left transition dark:border-slate-800 ${active ? 'bg-indigo-50 dark:bg-indigo-500/10' : 'hover:bg-slate-50 dark:hover:bg-slate-900/60'}`}><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${pending ? 'bg-amber-400' : row.status === 'approved' || row.status === 'succeeded' ? 'bg-emerald-500' : 'bg-slate-300'}`} /><b className="min-w-0 flex-1 truncate text-sm">{title}</b><span className="text-[10px] text-muted">{formatTime(row.requestedAt)}</span></div><div className="mt-1 flex items-center justify-between pl-4 text-xs text-muted"><span className="truncate">{row.requesterName}</span><span>{statusLabel(row.status)}</span></div></button>;
}

function ApprovalDetail({ item, pending, onApprove, onReject }: { item: ApprovalItem; pending: boolean; onApprove: () => void; onReject: () => void }) {
  const qc = useQueryClient();
  const row = item.row; const canDecide = row.status === 'pending' || row.status === 'pending_approval';
  const analysis = useQuery<any>({ queryKey: ['database-approval-analysis', row.id], enabled: item.type === 'sql', queryFn: async () => (await api.get(`/db-query/approvals/${row.id}/analysis`)).data, staleTime: Infinity, retry: false });
  const refreshAnalysis = async () => {
    const fresh = (await api.get(`/db-query/approvals/${row.id}/analysis?refresh=true`)).data;
    qc.setQueryData(['database-approval-analysis', row.id], fresh);
  };
  const approvers = item.type === 'sql' ? row.datasource.approvers || [] : (row.kind === 'migration' ? row.targetDatasource?.approvers : row.sourceDatasource?.approvers) || [];
  return <div className="p-5 sm:p-7"><div className="flex flex-wrap items-start gap-4 border-b pb-5 dark:border-slate-800"><div className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10 dark:text-indigo-300"><Database size={20} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold">{item.type === 'sql' ? `${row.operation.toUpperCase()} · ${row.datasource.name}` : `${transferLabel(row.kind)} · ${row.sourceDatasource.name}`}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] dark:bg-slate-800">{statusLabel(row.status)}</span></div><p className="mt-1 text-xs text-muted">提交于 {new Date(row.requestedAt).toLocaleString()}</p></div>{canDecide && <div className="flex gap-2"><button className="btn btn-secondary text-red-500" disabled={pending} onClick={onReject}><X size={14} />拒绝</button><button className="btn btn-primary" disabled={pending} onClick={onApprove}><Check size={14} />审批通过</button></div>}</div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><InfoCard icon={<User size={15} />} title="申请人"><p className="font-medium">{row.requesterName}</p><p className="text-xs text-muted">申请人在审批人列表中时可以自审</p></InfoCard><InfoCard icon={<ShieldCheck size={15} />} title={`审批人列表 · ${approvers.length}`}><div className="flex flex-wrap gap-2">{approvers.map((user: any) => <span key={user.id} className="rounded-lg bg-slate-100 px-2 py-1 text-xs dark:bg-slate-800">{user.displayName || user.username}</span>)}{!approvers.length && <span className="text-xs text-red-500">未配置审批人</span>}</div></InfoCard></div>
    {item.type === 'sql' ? <><section className="mt-5"><h3 className="mb-2 text-sm font-semibold">提交的 SQL</h3><pre className="max-h-64 overflow-auto whitespace-pre-wrap break-all rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-100">{row.sql}</pre></section><SqlAnalysis data={analysis.data} loading={analysis.isLoading} error={analysis.error} canRefresh={row.status === 'pending'} onRetry={() => analysis.refetch()} onRefresh={refreshAnalysis} /></> : <TransferDetail row={row} />}
    {row.error && <div className="mt-5 rounded-xl bg-red-50 p-3 text-xs text-red-600 dark:bg-red-500/10 dark:text-red-300">{row.error}</div>}
  </div>;
}

function SqlAnalysis({ data, loading, error, canRefresh, onRetry, onRefresh }: { data: any; loading: boolean; error: any; canRefresh: boolean; onRetry: () => void; onRefresh: () => void }) {
  const errorMessage = error?.response?.data?.message || error?.message;
  return <section className="mt-5"><div className="mb-2 flex items-center gap-2"><Gauge size={15} className="text-indigo-500" /><h3 className="text-sm font-semibold">SQL 执行计划分析</h3><span className="text-[10px] text-muted">{data?.cached ? '历史快照' : 'EXPLAIN，不会实际执行 SQL'}{data?.analyzedAt ? ` · ${new Date(data.analyzedAt).toLocaleString()}` : ''}</span></div>{loading ? <div className="card p-6 text-center text-xs text-muted">正在生成执行计划…</div> : error ? <div className="flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-xs text-red-600 dark:border-red-500/20 dark:bg-red-500/10 dark:text-red-300"><AlertCircle size={16} /><span className="min-w-0 flex-1">分析请求失败：{String(errorMessage || '未知错误')}</span><button className="btn btn-secondary" onClick={onRetry}><RefreshCw size={13} />重试</button></div> : !data?.available ? <div className="flex items-start gap-3 rounded-xl border border-dashed p-4 text-xs text-muted"><AlertCircle size={16} className="mt-0.5 shrink-0" /><div className="min-w-0 flex-1"><p>{data?.reason || '服务端未返回分析结果'}</p>{data?.warnings?.map((warning: string) => <p key={warning} className="mt-2 text-amber-600">{warning}</p>)}</div>{canRefresh && <button className="btn btn-secondary" onClick={onRefresh}><RefreshCw size={13} />重新分析</button>}</div> : <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-3"><Metric label="预计扫描/影响行" value={data.estimatedRows ?? '-'} /><Metric label="使用索引" value={data.usedIndexes?.join(', ') || '未使用'} /><Metric label="预计总成本" value={data.totalCost ?? '-'} /></div>{!!data.warnings?.length && <div className="rounded-xl bg-amber-50 p-3 text-xs text-amber-700 dark:bg-amber-500/10 dark:text-amber-300">{data.warnings.map((warning: string) => <p key={warning} className="flex gap-2"><AlertTriangle size={13} />{warning}</p>)}</div>}<div className="overflow-x-auto rounded-xl border dark:border-slate-800"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-muted dark:bg-slate-900"><tr><th className="px-3 py-2">表/节点</th><th className="px-3 py-2">访问方式</th><th className="px-3 py-2">索引</th><th className="px-3 py-2">预计行数</th><th className="px-3 py-2">条件/附加信息</th></tr></thead><tbody>{data.steps?.map((step: any, index: number) => <tr key={index} className="border-t dark:border-slate-800"><td className="px-3 py-2 font-mono">{step.table || step.relation || step.nodeType || '-'}</td><td className="px-3 py-2">{step.accessType || step.nodeType || '-'}</td><td className="px-3 py-2 font-mono">{step.usedKey || step.indexName || '-'}</td><td className="px-3 py-2">{step.estimatedRows}</td><td className="max-w-sm truncate px-3 py-2" title={step.extra || step.filter}>{step.extra || step.filter || '-'}</td></tr>)}</tbody></table></div>{canRefresh && <div className="text-right"><button className="btn btn-secondary" onClick={onRefresh}><RefreshCw size={13} />重新分析</button></div>}</div>}</section>;
}

function TransferDetail({ row }: { row: any }) { return <section className="mt-5"><h3 className="mb-2 text-sm font-semibold">申请内容</h3><div className="grid gap-3 rounded-xl border p-4 text-xs dark:border-slate-800 sm:grid-cols-2"><p><span className="text-muted">来源数据库：</span>{row.sourceDatabase}</p><p><span className="text-muted">目标数据库：</span>{row.targetDatabase || '-'}</p><p className="sm:col-span-2"><span className="text-muted">数据表：</span>{row.tables.join(', ')}</p><p><span className="text-muted">冲突策略：</span>{row.conflictStrategy}</p><p><span className="text-muted">任务进度：</span>{row.completedTables}/{row.totalTables}</p></div></section>; }
function InfoCard({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <div className="rounded-xl border p-4 dark:border-slate-800"><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-muted">{icon}{title}</div>{children}</div>; }
function Metric({ label, value }: { label: string; value: any }) { return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="text-[10px] text-muted">{label}</p><p className="mt-1 truncate text-sm font-semibold" title={String(value)}>{value}</p></div>; }
function transferLabel(kind: string) { return ({ backup: 'JSONL 备份', native_backup: '原生备份', native_restore: '原生恢复', migration: '数据库迁移' } as Record<string, string>)[kind] || kind; }
function statusLabel(status: string) { return ({ pending: '待审批', pending_approval: '待审批', executing: '执行中', approved: '已通过', queued: '排队中', running: '执行中', succeeded: '已完成', rejected: '已拒绝', failed: '失败', cancelled: '已取消' } as Record<string, string>)[status] || status; }
function formatTime(value: string) { const date = new Date(value); return `${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')} ${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`; }
