import { useMemo, useState } from 'react';
import { Ban, Clipboard, Download, FileKey2, KeyRound, Plus, TicketCheck, Upload } from 'lucide-react';
import { useAdminUsers } from '../../hooks/useAdmin';
import { useLicenseAdmin } from '../../hooks/useLicenses';
import { Select } from '../common/Select';
import { Card, PageHeader, errText } from '../Settings/ui';

const EDITIONS = [{ value: 'personal-pro', label: 'Personal Pro' }, { value: 'team', label: 'Team' }, { value: 'enterprise', label: 'Enterprise' }];

export function LicensesPage() {
  const users = useAdminUsers(); const licenses = useLicenseAdmin();
  const [showAssign, setShowAssign] = useState(false); const [showCode, setShowCode] = useState(false); const [error, setError] = useState(''); const [issuedCode, setIssuedCode] = useState('');
  const [offlineUserId, setOfflineUserId] = useState(''); const [offlineChallenge, setOfflineChallenge] = useState<Record<string, unknown>>(); const [offlineFileName, setOfflineFileName] = useState('');
  const [assignment, setAssignment] = useState({ userId: '', edition: 'personal-pro', expiresAt: futureDate(365), graceDays: 7, maxDevices: 3 });
  const [codeForm, setCodeForm] = useState({ edition: 'personal-pro', durationDays: 365, graceDays: 7, maxDevices: 3, maxRedemptions: 1 });
  const userOptions = useMemo(() => (users.data || []).map((user) => ({ value: user.id, label: `${user.displayName || user.username}${user.email ? ` · ${user.email}` : ''}` })), [users.data]);
  async function assign() { setError(''); try { await licenses.assign.mutateAsync({ ...assignment, expiresAt: new Date(assignment.expiresAt).toISOString() }); setShowAssign(false); } catch (reason) { setError(errText(reason)); } }
  async function createCode() { setError(''); try { const result = await licenses.createCode.mutateAsync(codeForm); setIssuedCode(result.code); setShowCode(false); } catch (reason) { setError(errText(reason)); } }
  async function readOfflineChallenge(file?: File) {
    if (!file) return; setError('');
    try {
      if (file.size > 64 * 1024) throw new Error('离线申请文件过大');
      const value = JSON.parse(await file.text()) as Record<string, unknown>;
      if (value.format !== 'code-studio-license-request-v1' || typeof value.deviceId !== 'string' || typeof value.nonce !== 'string') throw new Error('不是有效的 Code Studio 离线申请文件');
      setOfflineChallenge(value); setOfflineFileName(file.name);
    } catch (reason) { setOfflineChallenge(undefined); setOfflineFileName(''); setError(errText(reason)); }
  }
  async function issueOffline() {
    if (!offlineUserId || !offlineChallenge) return; setError('');
    try {
      const response = await licenses.issueOffline.mutateAsync({ userId: offlineUserId, challenge: offlineChallenge });
      const blob = new Blob([`${JSON.stringify(response, null, 2)}\n`], { type: 'application/json' }); const url = URL.createObjectURL(blob);
      const link = document.createElement('a'); link.href = url; link.download = `code-studio-${String(offlineChallenge.deviceId).slice(0, 8)}.license.json`; link.click(); URL.revokeObjectURL(url);
    } catch (reason) { setError(errText(reason)); }
  }
  return <div><PageHeader title="许可证" desc="管理个人、团队和企业套餐，以及一次性或批量兑换码。兑换码原文只在创建时展示一次。" action={<div className="flex gap-2"><button className="btn btn-ghost btn-sm" onClick={() => setShowCode((value) => !value)}><TicketCheck size={14} />生成兑换码</button><button className="btn btn-primary btn-sm" onClick={() => setShowAssign((value) => !value)}><Plus size={14} />分配套餐</button></div>} />
    {error && <div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-600">{error}</div>}
    {issuedCode && <div className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-900 dark:bg-amber-950/20"><div className="text-xs font-bold text-amber-800 dark:text-amber-300">请立即安全交付，关闭后无法再次查看</div><div className="mt-2 flex items-center gap-2"><code className="min-w-0 flex-1 break-all rounded-lg bg-white px-3 py-2 text-sm dark:bg-slate-900">{issuedCode}</code><button className="btn btn-ghost btn-sm" onClick={() => void navigator.clipboard.writeText(issuedCode)}><Clipboard size={13} />复制</button><button className="icon-btn" onClick={() => setIssuedCode('')}>×</button></div></div>}
    {showAssign && <Card title="分配或更新套餐"><div className="grid gap-3 md:grid-cols-2"><Labeled label="用户"><Select className="w-full" value={assignment.userId} placeholder="选择用户" options={userOptions} onChange={(userId) => setAssignment((value) => ({ ...value, userId }))} /></Labeled><Labeled label="版本"><Select className="w-full" value={assignment.edition} options={EDITIONS} onChange={(edition) => setAssignment((value) => ({ ...value, edition }))} /></Labeled><Labeled label="有效期至"><input className="input w-full" type="datetime-local" value={assignment.expiresAt} onChange={(event) => setAssignment((value) => ({ ...value, expiresAt: event.target.value }))} /></Labeled><Labeled label="设备上限"><input className="input w-full" type="number" min={1} max={100} value={assignment.maxDevices} onChange={(event) => setAssignment((value) => ({ ...value, maxDevices: Number(event.target.value) }))} /></Labeled></div><button className="btn btn-primary mt-4" disabled={!assignment.userId || licenses.assign.isPending} onClick={() => void assign()}>保存套餐</button></Card>}
    {showCode && <div className="mb-5"><Card title="生成兑换码"><div className="grid gap-3 md:grid-cols-3"><Labeled label="版本"><Select className="w-full" value={codeForm.edition} options={EDITIONS} onChange={(edition) => setCodeForm((value) => ({ ...value, edition }))} /></Labeled><NumberField label="有效天数" value={codeForm.durationDays} min={1} max={3650} onChange={(durationDays) => setCodeForm((value) => ({ ...value, durationDays }))} /><NumberField label="可兑换次数" value={codeForm.maxRedemptions} min={1} max={10000} onChange={(maxRedemptions) => setCodeForm((value) => ({ ...value, maxRedemptions }))} /><NumberField label="设备上限" value={codeForm.maxDevices} min={1} max={100} onChange={(maxDevices) => setCodeForm((value) => ({ ...value, maxDevices }))} /><NumberField label="离线宽限天数" value={codeForm.graceDays} min={0} max={90} onChange={(graceDays) => setCodeForm((value) => ({ ...value, graceDays }))} /></div><button className="btn btn-primary mt-4" disabled={licenses.createCode.isPending} onClick={() => void createCode()}><KeyRound size={14} />生成</button></Card></div>}
    <div className="mb-5"><Card title="签发离线许可证"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10"><FileKey2 size={18} /></span><p className="text-xs leading-5 text-muted">选择用户并导入其客户端生成的申请文件。签发结果只适用于申请中的设备和随机挑战，无法复制到其他设备。</p></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Labeled label="许可证用户"><Select className="w-full" value={offlineUserId} placeholder="选择已有套餐的用户" options={userOptions} onChange={setOfflineUserId} /></Labeled><Labeled label="离线申请文件"><label className="btn btn-secondary flex w-full cursor-pointer justify-start"><Upload size={14} /><span className="min-w-0 truncate">{offlineFileName || '选择 .json 申请文件'}</span><input type="file" accept="application/json,.json" className="hidden" onChange={(event) => void readOfflineChallenge(event.target.files?.[0])} /></label></Labeled></div>{offlineChallenge && <div className="mt-3 rounded-xl bg-slate-50 px-3 py-2 font-mono text-[10px] text-muted dark:bg-slate-900">设备 {String(offlineChallenge.deviceId).slice(0, 24)}… · 申请时间 {new Date(String(offlineChallenge.createdAt)).toLocaleString()}</div>}<button className="btn btn-primary mt-4" disabled={!offlineUserId || !offlineChallenge || licenses.issueOffline.isPending} onClick={() => void issueOffline()}>{licenses.issueOffline.isPending ? <FileKey2 size={14} /> : <Download size={14} />}签发并下载</button></Card></div>
    <div className="grid gap-5 xl:grid-cols-2"><Card title="用户套餐">{licenses.subscriptions.data?.length ? <div className="space-y-2">{licenses.subscriptions.data.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><KeyRound size={15} className="text-indigo-500" /><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{item.user.displayName || item.user.username}</div><div className="mt-1 text-[10px] text-muted">{editionName(item.edition)} · 至 {new Date(item.expiresAt).toLocaleDateString()} · {item.maxDevices} 台设备</div></div><span className={`badge ${item.status === 'active' ? 'badge-success' : ''}`}>{item.status}</span></div>)}</div> : <Empty>尚未分配套餐</Empty>}</Card>
      <Card title="兑换码">{licenses.codes.data?.length ? <div className="space-y-2">{licenses.codes.data.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><TicketCheck size={15} className="text-violet-500" /><div className="min-w-0 flex-1"><div className="font-mono text-xs font-semibold">{item.codePrefix}••••</div><div className="mt-1 text-[10px] text-muted">{editionName(item.edition)} · {item.durationDays} 天 · {item.redemptionCount}/{item.maxRedemptions}</div></div>{!item.disabledAt && <button className="icon-btn text-red-500" title="停用" onClick={() => void licenses.disableCode.mutateAsync(item.id)}><Ban size={13} /></button>}</div>)}</div> : <Empty>尚未生成兑换码</Empty>}</Card></div>
  </div>;
}

function Labeled({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs"><span className="mb-1 block text-muted">{label}</span>{children}</label>; }
function NumberField({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <Labeled label={label}><input className="input w-full" type="number" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} /></Labeled>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="py-10 text-center text-xs text-muted">{children}</div>; }
function editionName(value: string) { return EDITIONS.find((item) => item.value === value)?.label || value; }
function futureDate(days: number) { const date = new Date(Date.now() + days * 86400_000); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); }
