import { useEffect, useMemo, useState } from 'react';
import { Building2, Plus, Save, ShieldCheck, Trash2, UserPlus } from 'lucide-react';
import { useAdminUsers } from '../../hooks/useAdmin';
import { EnterprisePolicy, useOrganizationMembers, useOrganizations } from '../../hooks/useOrganizations';
import { Select } from '../common/Select';
import { Card, PageHeader, errText } from '../Settings/ui';
import { OrganizationInvitations } from './OrganizationInvitations';
import { OrganizationDomains } from './OrganizationDomains';

const DEFAULT_POLICY: EnterprisePolicy = { terminalEnabled: true, allowedModelEngines: ['codex-cli', 'claude-code', 'aider', 'openai-compatible', 'ollama'], allowedConnectorTypes: ['postgres', 'mysql', 'kafka', 'kubernetes'], allowedGitHosts: ['local'], allowedNetworkHosts: [], minimumClientVersion: '0.1.0', offlineDays: 7 };
export function OrganizationsPage() {
  const ops = useOrganizations(); const users = useAdminUsers(); const organizations = ops.organizations.data || [];
  const [selectedId, setSelectedId] = useState(''); const selected = organizations.find((item) => item.id === selectedId); const members = useOrganizationMembers(selectedId);
  const [creating, setCreating] = useState(false); const [form, setForm] = useState({ name: '', slug: '', seatLimit: 10 }); const [policy, setPolicy] = useState<EnterprisePolicy>(DEFAULT_POLICY); const [memberUserId, setMemberUserId] = useState(''); const [memberRole, setMemberRole] = useState('member'); const [error, setError] = useState('');
  useEffect(() => { if (!selectedId && organizations[0]) setSelectedId(organizations[0].id); }, [selectedId, organizations]);
  useEffect(() => { if (selected?.policy) setPolicy(selected.policy); }, [selected]);
  const userOptions = useMemo(() => (users.data || []).filter((user) => !members.data?.some((member) => member.userId === user.id)).map((user) => ({ value: user.id, label: user.displayName || user.username })), [users.data, members.data]);
  async function create() { setError(''); try { const result = await ops.create.mutateAsync(form); setCreating(false); setForm({ name: '', slug: '', seatLimit: 10 }); setSelectedId(result.data.id); } catch (reason) { setError(errText(reason)); } }
  async function savePolicy() { if (!selected) return; setError(''); try { await ops.savePolicy.mutateAsync({ id: selected.id, policy }); } catch (reason) { setError(errText(reason)); } }
  async function addMember() { if (!selected || !memberUserId) return; setError(''); try { await ops.addMember.mutateAsync({ id: selected.id, userId: memberUserId, role: memberRole }); setMemberUserId(''); } catch (reason) { setError(errText(reason)); } }
  return <div><PageHeader title="企业组织" desc="配置企业席位、员工账户和桌面客户端安全策略。" action={<button className="btn btn-primary btn-sm" onClick={() => setCreating((value) => !value)}><Plus size={14}/>创建组织</button>} />
    {error && <div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-600">{error}</div>}
    {selected && <div className="mb-5"><OrganizationInvitations key={selected.id} organizationId={selected.id}/></div>}
    {selected && <div className="mb-5"><OrganizationDomains key={selected.id} organizationId={selected.id}/></div>}
    {creating && <Card title="创建组织"><div className="grid gap-3 md:grid-cols-3"><Field label="组织名称" value={form.name} onChange={(name) => setForm((value) => ({ ...value, name }))}/><Field label="唯一标识" value={form.slug} onChange={(slug) => setForm((value) => ({ ...value, slug: slug.toLowerCase() }))}/><NumberField label="席位上限" value={form.seatLimit} onChange={(seatLimit) => setForm((value) => ({ ...value, seatLimit }))}/></div><button className="btn btn-primary mt-4" disabled={!form.name.trim() || !form.slug.trim() || ops.create.isPending} onClick={() => void create()}>创建</button></Card>}
    <div className="grid gap-5 xl:grid-cols-[300px_1fr]"><Card title="组织列表">{organizations.map((item) => <button key={item.id} className={`mb-2 flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selectedId === item.id ? 'border-indigo-300 bg-indigo-50 dark:bg-indigo-500/10' : 'border-slate-200 dark:border-slate-700'}`} onClick={() => setSelectedId(item.id)}><Building2 size={16} className="text-indigo-500"/><span className="min-w-0 flex-1"><b className="block truncate text-xs">{item.name}</b><span className="mt-1 block text-[10px] text-muted">{item._count.members}/{item.seatLimit} 席位 · {item.slug}</span></span></button>)}{!organizations.length && <p className="py-8 text-center text-xs text-muted">尚未创建企业组织</p>}</Card>
      {selected ? <div className="space-y-5"><PolicyCard value={policy} onChange={setPolicy} saving={ops.savePolicy.isPending} onSave={() => void savePolicy()}/><Card title="员工与角色"><div className="flex flex-wrap gap-2"><Select className="min-w-56 flex-1" value={memberUserId} placeholder="选择员工账户" options={userOptions} onChange={setMemberUserId}/><Select className="w-32" value={memberRole} options={[{value:'member',label:'成员'},{value:'admin',label:'管理员'},{value:'owner',label:'所有者'}]} onChange={setMemberRole}/><button className="btn btn-primary" disabled={!memberUserId || ops.addMember.isPending} onClick={() => void addMember()}><UserPlus size={14}/>添加</button></div><div className="mt-4 space-y-2">{members.data?.map((member) => <div key={member.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><ShieldCheck size={15} className="text-sky-500"/><div className="min-w-0 flex-1"><b className="block truncate text-xs">{member.user.displayName || member.user.username}</b><span className="text-[10px] text-muted">{member.role}</span></div><button className="icon-btn text-red-500" onClick={() => void ops.removeMember.mutateAsync({ id: selected.id, userId: member.userId })}><Trash2 size={13}/></button></div>)}</div></Card></div> : <Card title="企业配置"><p className="py-12 text-center text-xs text-muted">选择或创建组织</p></Card>}</div>
  </div>;
}
function PolicyCard({ value, onChange, saving, onSave }: { value: EnterprisePolicy; onChange: (value: EnterprisePolicy) => void; saving: boolean; onSave: () => void }) { const list = (key: keyof EnterprisePolicy, text: string) => onChange({ ...value, [key]: text.split(',').map((item) => item.trim()).filter(Boolean) }); return <Card title="桌面安全策略"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={value.terminalEnabled} onChange={(event) => onChange({ ...value, terminalEnabled: event.target.checked })}/>允许使用本地终端</label><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="允许的模型引擎（逗号分隔）" value={value.allowedModelEngines.join(', ')} onChange={(text) => list('allowedModelEngines', text)}/><Field label="允许的连接器" value={value.allowedConnectorTypes.join(', ')} onChange={(text) => list('allowedConnectorTypes', text)}/><Field label="允许的 Git 主机" value={value.allowedGitHosts.join(', ')} onChange={(text) => list('allowedGitHosts', text)}/><Field label="允许的网络主机" value={value.allowedNetworkHosts.join(', ')} onChange={(text) => list('allowedNetworkHosts', text)}/><Field label="最低客户端版本" value={value.minimumClientVersion} onChange={(minimumClientVersion) => onChange({ ...value, minimumClientVersion })}/><NumberField label="离线宽限天数" value={value.offlineDays} onChange={(offlineDays) => onChange({ ...value, offlineDays })}/></div><button className="btn btn-primary mt-4" disabled={saving} onClick={onSave}><Save size={14}/>保存并用于下次策略签发</button></Card>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-xs"><span className="mb-1 block text-muted">{label}</span><input className="input w-full" value={value} onChange={(event) => onChange(event.target.value)}/></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="block text-xs"><span className="mb-1 block text-muted">{label}</span><input className="input w-full" type="number" min={0} max={100000} value={value} onChange={(event) => onChange(Number(event.target.value))}/></label>; }
