FROM node:22-alpine AS build
WORKDIR /app
RUN apk add --no-cache git openssh-client openssl
COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
RUN npm ci --omit=optional
COPY apps/api apps/api
RUN npm run prisma:generate --workspace apps/api && npm run build --workspace apps/api
RUN npm prune --omit=dev --omit=optional

FROM node:22-alpine
WORKDIR /app
RUN apk add --no-cache git openssh-client docker-cli tini openssl postgresql16-client mariadb-client
ENV NODE_ENV=production
ENV NODE_PATH=/app/apps/api/node_modules:/app/node_modules
COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/node_modules node_modules
COPY --from=build /app/apps/api/package.json apps/api/package.json
COPY --from=build /app/apps/api/node_modules apps/api/node_modules
COPY --from=build /app/apps/api/dist apps/api/dist
COPY --from=build /app/apps/api/prisma apps/api/prisma
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "--require", "./apps/api/dist/instrumentation.js", "apps/api/dist/main.js"]
