import { useEffect, useState } from 'react';
import { Activity, ArrowLeft, BookOpenText, ChevronRight, GitBranch, Network, Plus, Save, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useMe } from '../../hooks/useMe';
import { Requirement, RequirementMetadata, RequirementProject, useRequirement, useRequirementList, useRequirementMetadata, useRequirementMutations, useRequirementRevisions, useStopRequirementPreview } from '../../hooks/useRequirements';
import { ACCESS } from '../../lib/access';
import { errText } from '../Settings/ui';
import { useFeedback } from '../common/FeedbackProvider';

const STAGE_LABEL: Record<string, string> = { design: '方案设计', development: '开发', testing: '测试', canary: '灰度', release: '上线' };
const STATUS_LABEL: Record<string, string> = { draft: '草稿', active: '进行中', completed: '已完成', cancelled: '已取消', archived: '已归档', pending: '待开始', in_progress: '进行中', blocked: '阻塞', skipped: '已跳过' };
const ACTIVITY_LABEL: Record<string, string> = { 'requirement.created': '创建了需求', 'requirement.updated': '更新了需求信息', 'requirement.document.saved': '保存了需求文档', 'requirement.stage.updated': '更新了流水线阶段', 'requirement.project.added': '关联了项目', 'requirement.project.updated': '调整了关联项目', 'requirement.project.removed': '解除了项目关联', 'requirement.branch.created': '创建了需求分支', 'requirement.preview.started': '发起了预览部署', 'requirement.preview.ready': '预览服务已就绪', 'requirement.preview.stopped': '主动停止了预览', 'requirement.preview.removed': '预览路由已移除', 'requirement.preview.lease_expired': '预览路由租约已过期' };

export function RequirementsPage() {
  const list = useRequirementList();
  const meta = useRequirementMetadata();
  const me = useMe();
  const [creating, setCreating] = useState(false);
  const canManage = !!me.data?.permissions.includes(ACCESS.requirementManage);
  const navigate = useNavigate();
  if (creating) return <main className="h-full overflow-y-auto p-5"><CreateRequirement teams={meta.data?.teams || []} currentUserId={me.data?.id} currentUsername={me.data?.username} onCancel={() => setCreating(false)} onCreated={(id) => navigate(`/requirements/${id}`)} /></main>;
  return <main className="h-full overflow-y-auto p-5"><div className="mx-auto max-w-6xl">
    <header className="mb-5 flex items-end justify-between gap-4"><div><div className="eyebrow">Delivery</div><h1 className="text-2xl font-bold">需求管理</h1><p className="mt-1 text-sm text-muted">集中查看需求排期、负责人和交付进度，点击需求进入独立详情。</p></div>{canManage && <button className="btn btn-primary" onClick={() => setCreating(true)}><Plus size={15}/>新建需求</button>}</header>
    <section className="card overflow-hidden"><div className="grid grid-cols-[minmax(0,1fr)_140px_120px_140px_48px] border-b border-slate-200 bg-slate-50/70 px-5 py-3 text-xs font-medium text-muted dark:border-slate-800 dark:bg-slate-950/40"><span>需求</span><span>负责人</span><span>状态</span><span>进度</span><span /></div>
      {list.isLoading ? <div className="py-16 text-center text-sm text-muted">正在读取需求…</div> : list.data?.items.map(item => <Link key={item.id} to={`/requirements/${item.id}`} className="grid grid-cols-[minmax(0,1fr)_140px_120px_140px_48px] items-center border-b border-slate-100 px-5 py-4 transition last:border-0 hover:bg-indigo-50/60 dark:border-slate-800 dark:hover:bg-indigo-500/5"><div className="min-w-0"><div className="font-mono text-[10px] text-indigo-600">{item.requirementNo}</div><div className="mt-1 truncate text-sm font-semibold">{item.title}</div><div className="mt-1 truncate text-xs text-muted">{item.summary || '暂无摘要'}</div></div><span className="truncate text-xs">{displayUser(item.owner)}</span><span className="text-xs">{STATUS_LABEL[item.status] || item.status}</span><div className="pr-5"><div className="mb-1 text-right text-[10px] text-muted">{item.progress}%</div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${item.progress}%` }} /></div></div><ChevronRight size={16} className="text-slate-400" /></Link>)}
      {!list.isLoading && !list.data?.items.length && <div className="py-16 text-center text-sm text-muted">暂无需求</div>}
    </section>
  </div></main>;
}

export function RequirementDetailPage() {
  const { id } = useParams(); const requirement = useRequirement(id); const me = useMe();
  if (requirement.isLoading) return <div className="grid h-full place-items-center text-sm text-muted">正在读取需求详情…</div>;
  if (!requirement.data) return <div className="grid h-full place-items-center text-sm text-muted">需求不存在或无权访问</div>;
  return <main className="h-full overflow-y-auto p-5"><div className="mx-auto mb-4 max-w-6xl"><Link to="/requirements" className="inline-flex items-center gap-1 text-xs text-muted hover:text-indigo-600"><ArrowLeft size={14}/>返回需求列表</Link></div><RequirementDetail requirement={requirement.data} currentUserId={me.data?.id || ''} isAdmin={!!me.data?.roles.includes('admin')} canManage={!!me.data?.permissions.includes(ACCESS.requirementManage)} canUpdateStage={!!me.data?.permissions.includes(ACCESS.requirementStageUpdate)} /></main>;
}

function RequirementProjectGovernance({ requirement, onUpdate }: { requirement: Requirement; onUpdate: (linkId: string, body: { developerId?: string; changeRequired?: boolean }) => void }) {
  const editable = requirement.projects.filter(link => !link.branchName && !link.sessionId);
  if (!editable.length) return null;
  return <section className="card p-4"><h2 className="text-sm font-bold">关联配置调整</h2><p className="mt-1 text-[10px] text-muted">仅尚未创建需求分支的服务可以调整；分支创建后负责人和改动范围被冻结。</p><div className="mt-3 space-y-2">{editable.map(link => <div key={link.id} className="grid items-center gap-2 rounded-xl border border-slate-200 p-3 text-xs dark:border-slate-800 md:grid-cols-[1fr_1fr_auto]"><div><div className="font-semibold">{link.project.name}</div><div className="font-mono text-indigo-600">{link.serviceKey}</div></div><select className="input h-9" aria-label={`${link.serviceKey}开发负责人`} value={link.developerId || ''} onChange={e => onUpdate(link.id, { developerId: e.target.value })}><option value="">未指派</option>{requirement.team.members.map(user => <option key={user.id} value={user.id}>{displayUser(user)}</option>)}</select><label className="flex items-center gap-2"><input type="checkbox" checked={link.changeRequired} onChange={e => onUpdate(link.id, { changeRequired: e.target.checked })}/>需要改动</label></div>)}</div></section>;
}

function StageRollback({ requirement, currentUserId, isOwner, onRollback }: { requirement: Requirement; currentUserId: string; isOwner: boolean; onRollback: (stageId: string, reason: string) => void }) {
  const stages = requirement.stages.filter(stage => (isOwner || stage.ownerId === currentUserId) && ['completed', 'skipped'].includes(stage.status));
  if (!stages.length) return null;
  return <section className="card p-4"><h2 className="text-sm font-bold">阶段回退</h2><p className="mt-1 text-[10px] text-muted">回退必须填写原因，并重新计算需求总进度。</p><div className="mt-3 flex flex-wrap gap-2">{stages.map(stage => <button key={stage.id} className="btn btn-ghost btn-sm" onClick={() => { const reason = window.prompt(`请输入“${STAGE_LABEL[stage.type]}”阶段的回退原因`)?.trim(); if (reason) onRollback(stage.id, reason); }}>回退：{STAGE_LABEL[stage.type]}</button>)}</div></section>;
}

function CreateRequirement({ teams, currentUserId, currentUsername, onCancel, onCreated }: { teams: RequirementMetadata['teams']; currentUserId?: string; currentUsername?: string; onCancel: () => void; onCreated: (id: string) => void }) {
  const mutation = useRequirementMutations().create; const { toast } = useFeedback();
  const [teamId, setTeamId] = useState(teams[0]?.id || ''); const [title, setTitle] = useState(''); const [summary, setSummary] = useState(''); const [plannedStartAt, setPlannedStartAt] = useState(''); const [plannedEndAt, setPlannedEndAt] = useState(''); const team = teams.find(item => item.id === teamId);
  useEffect(() => { if (!teamId && teams[0]) setTeamId(teams[0].id); }, [teamId, teams]);
  const submit = async () => { try { const response = await mutation.mutateAsync({ teamId, title, summary, plannedStartAt: plannedStartAt || undefined, plannedEndAt: plannedEndAt || undefined }); onCreated(response.data.id); toast('需求已创建'); } catch (error) { toast(errText(error), { title: '创建失败', tone: 'error' }); } };
  return <section className="mx-auto max-w-3xl"><h2 className="text-xl font-bold">创建需求</h2><p className="mt-1 text-sm text-muted">创建后自动生成唯一需求编号和五阶段交付流水线。</p><div className="card mt-5 space-y-4 p-5"><label className="block"><span className="label">项目组</span><select className="input mt-1 w-full" value={teamId} onChange={e => setTeamId(e.target.value)}>{teams.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block"><span className="label">标题</span><input className="input mt-1 w-full" maxLength={160} value={title} onChange={e => setTitle(e.target.value)}/></label><label className="block"><span className="label">负责人</span><select className="input mt-1 w-full" disabled><option>{team?.members.find(item => item.id === currentUserId)?.displayName || currentUsername || '当前用户'}</option></select></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">计划开始</span><input className="input mt-1 w-full" type="date" value={plannedStartAt} onChange={e => setPlannedStartAt(e.target.value)}/></label><label><span className="label">计划结束</span><input className="input mt-1 w-full" type="date" value={plannedEndAt} onChange={e => setPlannedEndAt(e.target.value)}/></label></div><label className="block"><span className="label">摘要</span><textarea className="input mt-1 min-h-24 w-full" maxLength={500} value={summary} onChange={e => setSummary(e.target.value)}/></label><div className="flex gap-2"><button className="btn btn-primary" disabled={!teamId || !title.trim() || mutation.isPending} onClick={submit}>创建需求</button><button className="btn btn-ghost" onClick={onCancel}>取消</button></div></div></section>;
}

function RequirementDetail({ requirement, currentUserId, isAdmin, canManage: canManagePermission, canUpdateStage: canUpdateStagePermission }: { requirement: Requirement; currentUserId: string; isAdmin: boolean; canManage: boolean; canUpdateStage: boolean }) {
  const mutations = useRequirementMutations(requirement.id, requirement.updatedAt); const { toast } = useFeedback();
  const revisions = useRequirementRevisions(requirement.id);
  const [title, setTitle] = useState(requirement.title); const [requirementSummary, setRequirementSummary] = useState(requirement.summary || ''); const [ownerId, setOwnerId] = useState(requirement.ownerId); const [plannedStartAt, setPlannedStartAt] = useState(dateInput(requirement.plannedStartAt)); const [plannedEndAt, setPlannedEndAt] = useState(dateInput(requirement.plannedEndAt));
  const [projectId, setProjectId] = useState(''); const [serviceKey, setServiceKey] = useState(''); const [developerId, setDeveloperId] = useState('');
  const metadata = useRequirementMetadata(); const teamMeta = metadata.data?.teams.find(team => team.id === requirement.teamId); const linked = new Set(requirement.projects.map(item => item.projectId)); const candidates = teamMeta?.projects.filter(item => !linked.has(item.id)) || [];
  const isOwner = requirement.ownerId === currentUserId || isAdmin;
  const mutable = ['draft', 'active'].includes(requirement.status); const canManage = canManagePermission && mutable; const canUpdateStage = canUpdateStagePermission && mutable;
  const canArchive = isOwner && canManagePermission && ['completed', 'cancelled'].includes(requirement.status);
  useEffect(() => { setTitle(requirement.title); setRequirementSummary(requirement.summary || ''); setOwnerId(requirement.ownerId); setPlannedStartAt(dateInput(requirement.plannedStartAt)); setPlannedEndAt(dateInput(requirement.plannedEndAt)); }, [requirement.id, requirement.title, requirement.summary, requirement.ownerId, requirement.plannedStartAt, requirement.plannedEndAt]);
  const act = async (job: () => Promise<unknown>, success: string) => { try { await job(); toast(success); } catch (error) { toast(errText(error), { title: '操作失败', tone: 'error' }); } };
  const addProject = () => act(() => mutations.addProject.mutateAsync({ projectId, serviceKey, developerId: developerId || undefined, changeRequired: true }), '项目已关联');
  return <div className="mx-auto max-w-6xl space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-mono text-xs text-indigo-600">{requirement.requirementNo}</div><h1 className="mt-1 text-2xl font-bold">{requirement.title}</h1><p className="mt-1 text-sm text-muted">{requirement.team.name} · 负责人 {displayUser(requirement.owner)} · {STATUS_LABEL[requirement.status] || requirement.status}</p></div><div className="flex items-center gap-2"><div className="rounded-xl bg-indigo-50 px-4 py-2 text-sm font-bold text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300">总进度 {requirement.progress}%</div>{canArchive && <button className="btn btn-secondary btn-sm" onClick={() => { if (window.confirm('归档后需求将完全只读，确认继续吗？')) void act(() => mutations.update.mutateAsync({ status: 'archived' }), '需求已归档'); }}>归档</button>}</div></header>
    {isOwner && canManage && <section className="card p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold">需求基本信息</h2><button className="btn btn-primary btn-sm" disabled={!title.trim() || mutations.update.isPending} onClick={() => void act(() => mutations.update.mutateAsync({ title, summary: requirementSummary, ownerId, plannedStartAt: plannedStartAt || undefined, plannedEndAt: plannedEndAt || undefined }), '需求信息已保存')}><Save size={13}/>保存</button></div><div className="grid gap-3 md:grid-cols-2"><label><span className="label">标题</span><input className="input mt-1 w-full" maxLength={160} value={title} onChange={e => setTitle(e.target.value)}/></label><label><span className="label">负责人</span><select className="input mt-1 w-full" value={ownerId} onChange={e => setOwnerId(e.target.value)}>{requirement.team.members.map(user => <option key={user.id} value={user.id}>{displayUser(user)}</option>)}</select></label><label><span className="label">计划开始</span><input className="input mt-1 w-full" type="date" value={plannedStartAt} onChange={e => setPlannedStartAt(e.target.value)}/></label><label><span className="label">计划结束</span><input className="input mt-1 w-full" type="date" value={plannedEndAt} onChange={e => setPlannedEndAt(e.target.value)}/></label><label className="md:col-span-2"><span className="label">摘要</span><textarea className="input mt-1 min-h-20 w-full" maxLength={500} value={requirementSummary} onChange={e => setRequirementSummary(e.target.value)}/></label></div><div className="mt-3 flex flex-wrap gap-2">{nextRequirementStatuses(requirement.status).map(status => <button key={status} className={status === 'cancelled' ? 'btn btn-ghost btn-sm text-red-600' : 'btn btn-secondary btn-sm'} onClick={() => { if ((status === 'cancelled' || status === 'archived') && !window.confirm(`确认将需求变更为“${STATUS_LABEL[status]}”吗？`)) return; void act(() => mutations.update.mutateAsync({ status }), `需求已变更为${STATUS_LABEL[status]}`); }}>{STATUS_LABEL[status]}</button>)}</div><p className="mt-2 text-[10px] text-muted">完成、取消或归档前必须先停止该需求的全部预览，包括启动失败但资源可能仍存在的实例；终态不能回退。</p></section>}
    <section className="card p-4"><h2 className="mb-3 text-sm font-bold">交付流水线</h2><div className="grid gap-3 xl:grid-cols-5">{requirement.stages.map(stage => { const editable = canUpdateStage && (isOwner || stage.ownerId === currentUserId); return <div key={stage.id} className="rounded-xl border border-slate-200 p-3 dark:border-slate-800"><div className="font-semibold">{STAGE_LABEL[stage.type] || stage.type}</div><div className="mt-1 text-[10px] text-muted">{displayUser(stage.owner)} · {STATUS_LABEL[stage.status] || stage.status}</div>{isOwner && canUpdateStage && <select aria-label={`${STAGE_LABEL[stage.type]}负责人`} className="input mt-2 h-8 w-full py-1 text-xs" value={stage.ownerId || ''} onChange={e => void act(() => mutations.updateStage.mutateAsync({ stageId: stage.id, ownerId: e.target.value }), '阶段负责人已更新')}><option value="">未指派</option>{requirement.team.members.map(user => <option key={user.id} value={user.id}>{displayUser(user)}</option>)}</select>}<textarea aria-label={`${STAGE_LABEL[stage.type]}负责内容`} className="input mt-2 min-h-16 w-full text-xs" defaultValue={stage.descriptionMarkdown} disabled={!editable} placeholder="负责内容与交付物" onBlur={e => { if (e.target.value !== stage.descriptionMarkdown) void act(() => mutations.updateStage.mutateAsync({ stageId: stage.id, descriptionMarkdown: e.target.value }), '阶段内容已更新'); }}/><input className="mt-3 w-full" type="range" min="0" max="100" value={stage.progress} disabled={!editable} onChange={e => void act(() => mutations.updateStage.mutateAsync({ stageId: stage.id, progress: Number(e.target.value) }), '阶段进度已更新')}/><div className="text-right text-[10px]">{stage.progress}%</div>{editable && <select className="input mt-2 h-8 w-full py-1 text-xs" value={stage.status} onChange={e => { const status = e.target.value; const blockedReason = status === 'blocked' ? window.prompt('请填写阻塞原因')?.trim() : undefined; if (status === 'blocked' && !blockedReason) return; void act(() => mutations.updateStage.mutateAsync({ stageId: stage.id, status, blockedReason }), '阶段状态已更新'); }}>{['pending','in_progress','completed','blocked','skipped'].map(status => <option key={status} value={status}>{STATUS_LABEL[status]}</option>)}</select>}</div>; })}</div></section>
    <section className="card flex flex-wrap items-center justify-between gap-4 p-5"><div><h2 className="flex items-center gap-2 text-sm font-bold"><BookOpenText size={16}/>详细需求文档</h2><p className="mt-1 text-xs text-muted">独立 Markdown 文档 · 当前版本 v{requirement.documentVersion} · 支持编辑、预览与修订历史</p></div><Link className="btn btn-primary" to={`/requirements/${requirement.id}/document`}><BookOpenText size={14}/>{isOwner && canManage ? '编辑详细文档' : '查看详细文档'}</Link></section>
    <section className="card p-4"><h2 className="mb-3 flex items-center gap-2 text-sm font-bold"><Network size={16}/>需求服务拓扑</h2><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="text-muted"><tr><th className="pb-2">服务 / 项目</th><th className="pb-2">开发负责人</th><th className="pb-2">分支</th><th className="pb-2">当前路由</th><th className="pb-2">运行位置</th></tr></thead><tbody>{requirement.projects.map(link => <ServiceRouteRow key={link.id} requirement={requirement} link={link}/>)}</tbody></table></div>{!requirement.projects.length && <div className="py-6 text-center text-xs text-muted">尚未关联服务；未关联服务不参与需求级路由。</div>}<p className="mt-3 text-[10px] text-muted">只有 Ready 且租约有效的实例走需求预览；其他状态由路由控制面尝试使用项目配置的测试环境，未配置时会明确返回不可用。</p></section>
    <section className="card p-4"><h2 className="mb-3 text-sm font-bold">关联项目与需求分支</h2><div className="space-y-2">{requirement.projects.map(link => <div key={link.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-200 p-3 text-xs dark:border-slate-800"><div className="min-w-44 flex-1"><div className="font-semibold">{link.project.name} <span className="font-mono text-indigo-600">{link.serviceKey}</span></div><div className="mt-1 text-muted">开发：{displayUser(link.developer)} · {link.branchName || '尚未创建分支'}</div></div>{link.developerId === currentUserId && !link.branchName && link.changeRequired && <button className="btn btn-primary btn-sm" onClick={() => void act(() => mutations.createBranch.mutateAsync(link.id), '需求分支已创建')}><GitBranch size={13}/>创建需求分支</button>}{isOwner && canManage && <button className="btn btn-ghost btn-sm" onClick={() => void act(() => mutations.removeProject.mutateAsync(link.id), '关联已解除')}><Trash2 size={13}/></button>}</div>)}</div>{isOwner && canManage && <div className="mt-4 grid gap-2 md:grid-cols-[1fr_1fr_1fr_auto]"><select className="input" value={projectId} onChange={e => setProjectId(e.target.value)}><option value="">选择项目</option>{candidates.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className="input" value={serviceKey} onChange={e => setServiceKey(e.target.value)} placeholder="服务标识，如 order-api"/><select className="input" value={developerId} onChange={e => setDeveloperId(e.target.value)}><option value="">选择开发负责人</option>{requirement.team.members.map(user => <option key={user.id} value={user.id}>{displayUser(user)}</option>)}</select><button className="btn btn-primary" disabled={!projectId || !serviceKey.trim() || !developerId} onClick={addProject}><Plus size={13}/>关联</button></div>}</section>
    <div className="grid gap-5 lg:grid-cols-2"><section className="card p-4"><h2 className="mb-3 flex items-center gap-2 text-sm font-bold"><BookOpenText size={16}/>文档修订历史</h2><div className="space-y-3">{revisions.data?.items.map(item => <div key={item.id} className="border-l-2 border-indigo-300 pl-3 text-xs"><div className="font-semibold">v{item.version} · {item.changeSummary || '未填写修改说明'}</div><div className="mt-1 text-muted">{displayUser(item.createdBy)} · {formatTime(item.createdAt)}</div></div>)}</div>{!revisions.isLoading && !revisions.data?.items.length && <div className="text-xs text-muted">暂无修订记录</div>}</section><section className="card p-4"><h2 className="mb-3 flex items-center gap-2 text-sm font-bold"><Activity size={16}/>需求活动</h2><div className="max-h-80 space-y-3 overflow-y-auto">{requirement.activities.map(item => <div key={item.id} className="border-l-2 border-slate-200 pl-3 text-xs dark:border-slate-700"><div className="font-semibold">{item.actor ? displayUser(item.actor) : '系统'} {ACTIVITY_LABEL[item.action] || item.action}</div><div className="mt-1 text-muted">{activityDetail(item.detail)} · {formatTime(item.createdAt)}</div></div>)}</div>{!requirement.activities.length && <div className="text-xs text-muted">暂无活动记录</div>}</section></div>
    {isOwner && canManage && (
      <RequirementProjectGovernance requirement={requirement} onUpdate={(linkId, body) => void act(() => mutations.updateProject.mutateAsync({ linkId, ...body }), '关联配置已更新')}/>
    )}
    {canUpdateStage && ['draft', 'active'].includes(requirement.status) && (
      <StageRollback requirement={requirement} currentUserId={currentUserId} isOwner={isOwner} onRollback={(stageId, transitionReason) => void act(() => mutations.updateStage.mutateAsync({ stageId, status: 'in_progress', transitionReason }), '阶段已回退')}/>
    )}
  </div>;
}

function ServiceRouteRow({ requirement, link }: { requirement: Requirement; link: RequirementProject }) {
  const me = useMe(); const stop = useStopRequirementPreview(requirement.id); const { toast } = useFeedback();
  const endpoint = requirement.routeEndpoints.find(item => item.serviceKey === link.serviceKey);
  const preview = requirement.previews.find(item => item.serviceKey === link.serviceKey && ['starting', 'ready', 'failed'].includes(item.status));
  const route = endpoint ? '需求预览' : preview?.status === 'starting' ? '预览启动中 → 测试回退' : preview?.status === 'failed' ? '预览失败 → 测试回退' : '测试回退（需配置）';
  const canStop = !!preview && link.developerId === me.data?.id && !!me.data?.permissions.includes(ACCESS.generate);
  const stopPreview = async () => { if (!preview || !window.confirm(`确认停止 ${link.serviceKey} 的需求预览吗？`)) return; try { await stop.mutateAsync(preview.sessionId); toast('需求预览已停止'); } catch (error) { toast(errText(error), { title: '停止失败', tone: 'error' }); } };
  return <tr className="border-t border-slate-100 dark:border-slate-800">
    <td className="py-3"><div className="font-semibold">{link.serviceKey}</div><div className="text-muted">{link.project.name} · {link.changeRequired ? '需要改动' : '无需改动'}</div></td>
    <td className="py-3">{displayUser(link.developer)}</td>
    <td className="max-w-52 truncate py-3 font-mono text-[10px]" title={link.branchName || undefined}>{link.branchName || '—'}</td>
    <td className="py-3"><span className={endpoint ? 'text-emerald-600' : 'text-amber-600'}>{route}</span>{endpoint && <div className="text-[10px] text-muted">租约至 {formatTime(endpoint.leaseExpiresAt)}</div>}</td>
    <td className="py-3">{endpoint ? <><div>{endpoint.namespace} / {endpoint.serviceName}:{endpoint.port}</div>{endpoint.publicUrl && <a className="text-indigo-600 hover:underline" href={endpoint.publicUrl} target="_blank" rel="noreferrer">打开预览</a>}</> : <span className="text-muted">由运行目标的测试环境绑定决定</span>}{canStop && <button className="btn btn-ghost btn-sm mt-2 block text-red-600" disabled={stop.isPending} onClick={() => void stopPreview()}>停止我的预览</button>}</td>
  </tr>;
}

function displayUser(user?: { username: string; displayName?: string | null } | null) { return user?.displayName || user?.username || '未指派'; }
function formatTime(value: string) { return new Intl.DateTimeFormat('zh-CN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)); }
function activityDetail(detail?: Record<string, unknown> | null) { if (!detail) return '无附加信息'; const service = typeof detail.serviceKey === 'string' ? `服务 ${detail.serviceKey}` : ''; const version = typeof detail.version === 'number' ? `版本 v${detail.version}` : ''; const stage = typeof detail.stage === 'string' ? `阶段 ${STAGE_LABEL[detail.stage] || detail.stage}` : ''; const reason = typeof detail.transitionReason === 'string' ? `原因：${detail.transitionReason}` : typeof detail.blockedReason === 'string' ? `原因：${detail.blockedReason}` : ''; return [service, version, stage, reason].filter(Boolean).join(' · ') || '已记录详细变更'; }
function dateInput(value?: string | null) { return value ? value.slice(0, 10) : ''; }
function nextRequirementStatuses(status: string) { const next: Record<string, string[]> = { draft: ['active', 'cancelled'], active: ['completed', 'cancelled'], completed: ['archived'], cancelled: ['archived'], archived: [] }; return next[status] || []; }
