import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { RefreshCw, Send, RadioTower } from 'lucide-react';
import { api } from '../../lib/api';
import { useFeedback } from '../common/FeedbackProvider';
import { useMe } from '../../hooks/useMe';

type Topic = { name:string; internal:boolean; partitions:Array<{partition:number;leader:number;replicas:number[];isr:number[];low:string;high:string}> };
type ListResult<T> = { items:T[]; total:number; truncated:boolean };
type TopicMetrics = { topic:string; measuredAt:string; retained:string; windows:Record<'5m'|'1h'|'24h',string>; partitions:Array<{partition:number;retained:string;windows:Record<'5m'|'1h'|'24h',string>}> };
type GroupLag = { groupId:string; measuredAt:string; lag:string; truncated:boolean; topics:Array<{topic:string;lag:string;partitions:Array<{partition:number;committed:string;low:string;high:string;lag:string}>}> };
type ProduceResult = { topic:string; records:Array<{partition:number;offset:string}> };
type Consumer = { memberId:string;clientId:string;clientHost:string;status:'working'|'idle'|'rebalancing';partitionCount:number;assignment:Array<{topic:string;partitions:number[]}> };
type ConsumerGroup = { groupId:string;state:string;protocol:string;protocolType:string;members:number;consumers:Consumer[] };
type TopicConfig = { topic:string;entries:Array<{name:string;value:string|null;readOnly:boolean;isDefault:boolean;source:number;sensitive:boolean}> };

export function KafkaConsolePage() {
  const { toast } = useFeedback();
  const me = useMe(); const permissions=me.data?.permissions??[]; const canProduce=permissions.includes('kafka:produce'); const canTopics=permissions.includes('kafka:topic-manage'); const canGroups=permissions.includes('kafka:group-manage');
  const [topic,setTopic] = useState(''); const [showCreate,setShowCreate]=useState(false); const [value,setValue] = useState(''); const [key,setKey] = useState(''); const [producePartition,setProducePartition] = useState(''); const [groupOffsets,setGroupOffsets]=useState<{groupId:string;items:any[];lag:GroupLag} | null>(null);
  const topics = useQuery<ListResult<Topic>>({ queryKey:['kafka','topics'], queryFn:async()=> (await api.get('/kafka/topics')).data, retry:false });
  const groups = useQuery<ListResult<ConsumerGroup>>({ queryKey:['kafka','groups'], queryFn:async()=> (await api.get('/kafka/groups')).data, retry:false });
  const messages = useQuery<any>({ queryKey:['kafka','messages',topic], queryFn:async()=> (await api.get(`/kafka/topics/${encodeURIComponent(topic)}/messages`,{params:{limit:20,fromBeginning:true}})).data, enabled:!!topic, retry:false });
  const metrics = useQuery<TopicMetrics>({ queryKey:['kafka','metrics',topic], queryFn:async()=> (await api.get(`/kafka/topics/${encodeURIComponent(topic)}/metrics`)).data, enabled:!!topic, retry:false });
  const produce = useMutation({ mutationFn:async()=>(await api.post<ProduceResult>(`/kafka/topics/${encodeURIComponent(topic)}/messages`,{value,key:key||undefined,partition:producePartition===''?undefined:Number(producePartition)})).data, onSuccess:(result)=>{setValue('');const record=result.records[0];toast(record?`测试消息已写入：分区 ${record.partition}，Offset ${record.offset}`:'测试消息已写入 Kafka',{tone:'success'});void topics.refetch();void metrics.refetch();}, onError:(e:any)=>toast(e?.response?.data?.message||e.message,{tone:'error'}) });
  const manage = useMutation({ mutationFn:({method,url,data}:{method:'post'|'patch'|'delete';url:string;data?:unknown})=>api.request({method,url,data}), onSuccess:()=>{toast('Kafka 操作已完成',{tone:'success'});void topics.refetch();void groups.refetch();}, onError:(e:any)=>toast(e?.response?.data?.message||e.message,{tone:'error'}) });
  const confirmResource=(name:string)=>window.prompt(`危险操作：请输入资源名 ${name} 确认`)===name;
  const deleteTopic=()=>{if(topic&&confirmResource(topic))manage.mutate({method:'delete',url:`/kafka/topics/${encodeURIComponent(topic)}`,data:{confirmation:topic}});};
  const increasePartitions=()=>{const count=Number(window.prompt('新的分区总数'));if(count>0)manage.mutate({method:'patch',url:`/kafka/topics/${encodeURIComponent(topic)}/partitions`,data:{count}});};
  const truncateRecords=()=>{const partition=Number(window.prompt('分区'));const offset=window.prompt('删除该 Offset 之前的全部记录');if(offset&&confirmResource(topic))manage.mutate({method:'post',url:`/kafka/topics/${encodeURIComponent(topic)}/delete-records`,data:{partition,offset,confirmation:topic}});};
  const deleteGroup=(groupId:string)=>{if(confirmResource(groupId))manage.mutate({method:'delete',url:`/kafka/groups/${encodeURIComponent(groupId)}`,data:{confirmation:groupId}});};
  const setOffsets=(groupId:string)=>{const target=window.prompt('Topic');const raw=window.prompt('位点 JSON，例如 [{"partition":0,"offset":"100"}]');if(!target||!raw||!confirmResource(groupId))return;try{manage.mutate({method:'patch',url:`/kafka/groups/${encodeURIComponent(groupId)}/offsets`,data:{confirmation:groupId,topic:target,offsets:JSON.parse(raw)}});}catch{toast('位点 JSON 格式非法',{tone:'error'});}};
  const viewOffsets=async(groupId:string)=>{try{const [offsets,lag]=await Promise.all([api.get(`/kafka/groups/${encodeURIComponent(groupId)}/offsets`),api.get(`/kafka/groups/${encodeURIComponent(groupId)}/lag`)]);setGroupOffsets({groupId,items:offsets.data,lag:lag.data});}catch(e:any){toast(e?.response?.data?.message||e.message,{tone:'error'});}};
  const error = (topics.error as any)?.response?.data?.message;
  return <div className="h-full overflow-auto p-6"><div className="mx-auto max-w-7xl space-y-5">
    <header className="flex items-center justify-between"><div><h1 className="flex items-center gap-2 text-xl font-bold"><RadioTower size={20}/>Kafka 工作台</h1><p className="mt-1 text-xs text-muted">查看 Topic、分区与 Consumer Group，抽样消息不会提交业务消费位点。</p></div><div className="flex gap-2">{canTopics&&<button className="btn btn-primary" onClick={()=>setShowCreate(true)}>创建 Topic</button>}<button className="btn btn-secondary" onClick={()=>{void topics.refetch();void groups.refetch();}}><RefreshCw size={14}/>刷新</button></div></header>
    {showCreate&&<CreateTopicPanel onClose={()=>setShowCreate(false)} onCreated={name=>{setShowCreate(false);setTopic(name);void topics.refetch();}}/>}
    {error&&<div className="rounded-xl bg-red-50 p-4 text-sm text-red-600 dark:bg-red-500/10">{error}</div>}
    <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><section className="card overflow-hidden"><div className="border-b p-4 font-semibold dark:border-slate-800">Topics · {topics.data?.total??0}{topics.data?.truncated?'（展示前 500）':''}</div><div className="max-h-[680px] overflow-auto">{topics.data?.items.filter(x=>!x.internal).map(item=><button key={item.name} onClick={()=>{setTopic(item.name);setProducePartition('');}} className={`block w-full border-b p-4 text-left dark:border-slate-800 ${topic===item.name?'bg-indigo-50 dark:bg-indigo-500/10':'hover:bg-slate-50 dark:hover:bg-slate-900'}`}><b className="break-all text-sm">{item.name}</b><div className="mt-1 text-[10px] text-muted">{item.partitions.length} 个分区 · {sumPartitionOffsets(item.partitions)} 条保留记录</div></button>)}</div></section>
      <div className="space-y-5">{topic?<><section className="card p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">{topic}</h2>{canTopics&&<div className="flex flex-wrap gap-2"><button className="btn btn-secondary btn-sm" onClick={increasePartitions}>增加分区</button><button className="btn btn-secondary btn-sm text-amber-600" onClick={truncateRecords}>截断消息</button><button className="btn btn-secondary btn-sm text-red-600" onClick={deleteTopic}>删除 Topic</button></div>}</div>{metrics.error&&<p className="mt-3 text-xs text-red-500">消息统计读取失败</p>}<div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><KafkaMetric label="当前保留" value={metrics.data?.retained}/><KafkaMetric label="最近 5 分钟" value={metrics.data?.windows['5m']}/><KafkaMetric label="最近 1 小时" value={metrics.data?.windows['1h']}/><KafkaMetric label="最近 24 小时" value={metrics.data?.windows['24h']}/></div><p className="mt-2 text-[10px] text-muted">消息量根据分区 Offset 差值估算；压缩 Topic 或事务记录场景可能与实际消息条数存在偏差。</p><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-muted"><tr><th>分区</th><th>Leader</th><th>副本</th><th>ISR</th><th>Low</th><th>High</th><th>5 分钟</th><th>1 小时</th><th>24 小时</th></tr></thead><tbody>{topics.data?.items.find(x=>x.name===topic)?.partitions.map(p=>{const metric=metrics.data?.partitions.find(item=>item.partition===p.partition);return <tr key={p.partition} className="border-t dark:border-slate-800"><td className="py-2">{p.partition}</td><td>{p.leader}</td><td>{p.replicas.join(', ')}</td><td>{p.isr.join(', ')}</td><td>{p.low}</td><td>{p.high}</td><td>{formatOffset(metric?.windows['5m'])}</td><td>{formatOffset(metric?.windows['1h'])}</td><td>{formatOffset(metric?.windows['24h'])}</td></tr>})}</tbody></table></div></section>
      <TopicConfigPanel key={topic} topic={topic} canManage={canTopics}/>
      <section className="card p-5"><div className="flex justify-between"><h2 className="font-bold">消息抽样</h2><button className="icon-btn" onClick={()=>messages.refetch()}><RefreshCw size={14}/></button></div><div className="mt-3 space-y-2">{messages.data?.items?.map((m:any)=><article key={`${m.partition}-${m.offset}`} className="rounded-xl border p-3 text-xs dark:border-slate-800"><div className="mb-2 flex gap-3 text-[10px] text-muted"><span>分区 {m.partition}</span><span>Offset {m.offset}</span><span>{m.timestamp?new Date(Number(m.timestamp)).toLocaleString():'-'}</span></div><pre className="max-h-40 overflow-auto whitespace-pre-wrap break-all">{m.value??'null'}</pre></article>)}{!messages.isLoading&&!messages.data?.items?.length&&<p className="py-8 text-center text-xs text-muted">采样窗口内没有读取到消息</p>}</div></section>
      {canProduce&&<section className="card p-5"><div><h2 className="font-bold">测试发送</h2><p className="mt-1 text-xs text-amber-600 dark:text-amber-400">该操作会向当前 Topic 真实写入一条消息，并记录发送审计；请勿向生产 Topic 写入无效数据。</p></div><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_180px]"><input className="input w-full" placeholder="Key（可选）" value={key} onChange={e=>setKey(e.target.value)}/><select className="input w-full" aria-label="目标分区" value={producePartition} onChange={e=>setProducePartition(e.target.value)}><option value="">自动选择分区</option>{topics.data?.items.find(item=>item.name===topic)?.partitions.map(partition=><option key={partition.partition} value={partition.partition}>分区 {partition.partition}</option>)}</select></div><textarea className="input mt-3 min-h-32 w-full font-mono text-xs" placeholder="消息内容，最多 1 MiB" value={value} onChange={e=>setValue(e.target.value)}/><div className="mt-3 flex justify-end"><button className="btn btn-primary" disabled={!value||produce.isPending} onClick={()=>produce.mutate()}><Send size={14}/>{produce.isPending?'发送中…':'测试发送（真实写入）'}</button></div></section>}</>:<div className="card grid min-h-64 place-items-center text-sm text-muted">从左侧选择 Topic</div>}</div></div>
    <section className="card p-5"><h2 className="font-bold">Consumer Groups · {groups.data?.total??0}{groups.data?.truncated?'（展示前 500）':''}</h2><div className="mt-3 grid gap-3 lg:grid-cols-2">{groups.data?.items.map(g=><div key={g.groupId} className="rounded-xl border p-4 text-xs dark:border-slate-800"><div className="flex items-start justify-between gap-3"><div><b className="break-all">{g.groupId}</b><div className="mt-1 text-muted">{g.state} · {g.protocol||'-'}</div></div><span className="shrink-0 rounded-full bg-indigo-50 px-2.5 py-1 font-bold text-indigo-600 dark:bg-indigo-500/10">{g.members} 个消费者</span></div><ConsumerDetails consumers={g.consumers}/><div className="mt-3 flex flex-wrap gap-2"><button className="btn btn-secondary btn-sm" onClick={()=>void viewOffsets(g.groupId)}>查看位点与延迟</button>{canGroups&&<><button className="btn btn-secondary btn-sm" onClick={()=>setOffsets(g.groupId)}>设置位点</button><button className="btn btn-secondary btn-sm text-red-600" onClick={()=>deleteGroup(g.groupId)}>删除 Group</button></>}</div></div>)}</div>{groupOffsets&&<div className="mt-4 rounded-xl bg-slate-950 p-4 text-xs text-slate-100"><div className="flex flex-wrap items-center justify-between gap-2"><b>{groupOffsets.groupId}</b><span className="rounded-lg bg-amber-400/15 px-3 py-1 font-bold text-amber-300">当前总延迟 {formatOffset(groupOffsets.lag.lag)}</span></div>{groupOffsets.lag.truncated&&<p className="mt-2 text-amber-300">Topic 数量超过 500，仅统计前 500 个</p>}<div className="mt-3 max-h-72 overflow-auto"><table className="w-full text-left"><thead className="text-slate-400"><tr><th>Topic</th><th>分区</th><th>已提交</th><th>最新</th><th>延迟</th></tr></thead><tbody>{groupOffsets.lag.topics.flatMap(item=>item.partitions.map(partition=><tr key={`${item.topic}-${partition.partition}`} className="border-t border-slate-800"><td className="py-2 pr-3">{item.topic}</td><td>{partition.partition}</td><td>{partition.committed}</td><td>{partition.high}</td><td className="font-bold text-amber-300">{formatOffset(partition.lag)}</td></tr>))}</tbody></table></div><details className="mt-3"><summary className="cursor-pointer text-slate-400">查看原始位点数据</summary><pre className="mt-2 max-h-64 overflow-auto">{JSON.stringify(groupOffsets.items,null,2)}</pre></details></div>}</section>
  </div></div>;
}

function formatOffset(value?: string) {
  if (value == null) return '—';
  try { return BigInt(value).toLocaleString('zh-CN'); }
  catch { return value; }
}

function sumPartitionOffsets(partitions: Topic['partitions']) {
  try {
    return partitions.reduce((total, partition) => {
      const retained = BigInt(partition.high) - BigInt(partition.low);
      return total + (retained > 0n ? retained : 0n);
    }, 0n).toLocaleString('zh-CN');
  } catch { return '—'; }
}

function KafkaMetric({label,value}:{label:string;value?:string}) {
  return <div className="rounded-xl border border-slate-200 p-3 dark:border-slate-800"><div className="text-[10px] text-muted">{label}</div><div className="mt-1 text-lg font-bold">{formatOffset(value)}</div><div className="text-[10px] text-muted">条（Offset 估算）</div></div>;
}

function CreateTopicPanel({onClose,onCreated}:{onClose:()=>void;onCreated:(topic:string)=>void}) {
  const {toast}=useFeedback();
  const [draft,setDraft]=useState({topic:'',partitions:'3',replicationFactor:'3',cleanupPolicy:'delete',retentionMs:'',retentionBytes:'',maxMessageBytes:'',minInsyncReplicas:'',compressionType:'producer'});
  const numberValue=(value:string)=>value===''?undefined:Number(value);
  const optionalInteger=(value:string,minimum:number)=>value===''||(Number.isInteger(Number(value))&&Number(value)>=minimum);
  const partitions=Number(draft.partitions); const replicas=Number(draft.replicationFactor); const minIsr=numberValue(draft.minInsyncReplicas);
  const valid=/^[A-Za-z0-9._-]{1,249}$/.test(draft.topic)&&Number.isInteger(partitions)&&partitions>=1&&partitions<=10_000&&Number.isInteger(replicas)&&replicas>=1&&replicas<=100&&(minIsr==null||(Number.isInteger(minIsr)&&minIsr>=1&&minIsr<=replicas))&&optionalInteger(draft.retentionMs,60_000)&&optionalInteger(draft.retentionBytes,-1)&&optionalInteger(draft.maxMessageBytes,1_048_576);
  const create=useMutation({mutationFn:async()=>{const body={topic:draft.topic,partitions,replicationFactor:replicas,cleanupPolicy:draft.cleanupPolicy,compressionType:draft.compressionType,retentionMs:numberValue(draft.retentionMs),retentionBytes:numberValue(draft.retentionBytes),maxMessageBytes:numberValue(draft.maxMessageBytes),minInsyncReplicas:minIsr};return (await api.post<{topic:string}>('/kafka/topics',body)).data;},onSuccess:result=>{toast(`Topic ${result.topic} 已创建`,{tone:'success'});onCreated(result.topic);},onError:(e:any)=>toast(e?.response?.data?.message||e.message,{tone:'error'})});
  const field=(name:keyof typeof draft,value:string)=>setDraft(current=>({...current,[name]:value}));
  return <section className="card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">创建 Topic</h2><p className="mt-1 text-xs text-muted">分区数创建后只能增加；副本数不能通过当前工作台直接修改。</p></div><button className="btn btn-ghost btn-sm" onClick={onClose}>取消</button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs sm:col-span-3"><span className="mb-1 block font-semibold">Topic 名称</span><input className="input w-full" autoFocus value={draft.topic} onChange={event=>field('topic',event.target.value.trim())} placeholder="order-events"/></label><label className="text-xs"><span className="mb-1 block font-semibold">分区数</span><input className="input w-full" type="number" min="1" max="10000" value={draft.partitions} onChange={event=>field('partitions',event.target.value)}/></label><label className="text-xs"><span className="mb-1 block font-semibold">副本数</span><input className="input w-full" type="number" min="1" max="100" value={draft.replicationFactor} onChange={event=>field('replicationFactor',event.target.value)}/></label><label className="text-xs"><span className="mb-1 block font-semibold">最小同步副本</span><input className="input w-full" type="number" min="1" max={replicas||undefined} value={draft.minInsyncReplicas} onChange={event=>field('minInsyncReplicas',event.target.value)} placeholder="使用 Broker 默认值"/></label></div><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">高级配置</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><CreateSelect label="清理策略" description="按时间删除、按 Key 压缩，或同时启用。" value={draft.cleanupPolicy} options={['delete','compact','delete,compact']} onChange={value=>field('cleanupPolicy',value)}/><CreateSelect label="压缩方式" description="producer 表示沿用生产者消息的压缩编码。" value={draft.compressionType} options={['producer','uncompressed','gzip','snappy','lz4','zstd']} onChange={value=>field('compressionType',value)}/><CreateNumber label="保留时间（ms）" description="留空时使用 Broker 默认值，最小 60000。" value={draft.retentionMs} onChange={value=>field('retentionMs',value)}/><CreateNumber label="分区保留大小（bytes）" description="-1 表示不按容量限制。" value={draft.retentionBytes} onChange={value=>field('retentionBytes',value)}/><CreateNumber label="最大消息（bytes）" description="还需与生产者、消费者限制兼容。" value={draft.maxMessageBytes} onChange={value=>field('maxMessageBytes',value)}/></div></details>{minIsr!=null&&minIsr>replicas&&<p className="mt-3 text-xs text-red-500">最小同步副本数不能超过副本数。</p>}<div className="mt-4 flex justify-end"><button className="btn btn-primary" disabled={!valid||create.isPending} onClick={()=>create.mutate()}>{create.isPending?'创建中…':'创建 Topic'}</button></div></section>;
}

function CreateSelect({label,description,value,options,onChange}:{label:string;description:string;value:string;options:string[];onChange:(value:string)=>void}) {
  return <label className="text-xs"><span className="block font-semibold">{label}</span><span className="mb-2 block min-h-8 text-[10px] text-muted">{description}</span><select className="input w-full" value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option} value={option}>{option}</option>)}</select></label>;
}

function CreateNumber({label,description,value,onChange}:{label:string;description:string;value:string;onChange:(value:string)=>void}) {
  return <label className="text-xs"><span className="block font-semibold">{label}</span><span className="mb-2 block min-h-8 text-[10px] text-muted">{description}</span><input className="input w-full" type="number" value={value} onChange={event=>onChange(event.target.value)} placeholder="使用 Broker 默认值"/></label>;
}

const EDITABLE_TOPIC_CONFIGS = [
  {field:'cleanupPolicy',name:'cleanup.policy',label:'清理策略',description:'delete 按时间/容量删除；compact 按 Key 保留最新值；可同时启用。',options:['delete','compact','delete,compact']},
  {field:'retentionMs',name:'retention.ms',label:'保留时间（ms）',description:'消息最多保留多久，仅对包含 delete 的清理策略生效。',numeric:true},
  {field:'retentionBytes',name:'retention.bytes',label:'分区保留大小（bytes）',description:'每个分区允许保留的数据量上限，-1 表示不按容量限制。',numeric:true},
  {field:'maxMessageBytes',name:'max.message.bytes',label:'最大消息（bytes）',description:'Broker 接受的单批消息上限，还需与生产者和消费者限制保持兼容。',numeric:true},
  {field:'segmentMs',name:'segment.ms',label:'Segment 周期（ms）',description:'日志文件达到该时长后滚动，较小值会增加文件数量。',numeric:true},
  {field:'segmentBytes',name:'segment.bytes',label:'Segment 大小（bytes）',description:'单个日志 Segment 的目标大小，达到后滚动新文件。',numeric:true},
  {field:'minInsyncReplicas',name:'min.insync.replicas',label:'最小同步副本',description:'生产者使用 acks=all 时要求的最少同步副本数，不应超过有效副本能力。',numeric:true},
  {field:'compressionType',name:'compression.type',label:'压缩方式',description:'producer 保留生产者编码；也可由 Broker 强制指定压缩算法。',options:['producer','uncompressed','gzip','snappy','lz4','zstd']},
  {field:'deleteRetentionMs',name:'delete.retention.ms',label:'删除标记保留（ms）',description:'压缩 Topic 中墓碑消息可被消费者读取的保留时间。',numeric:true},
  {field:'minCompactionLagMs',name:'min.compaction.lag.ms',label:'最小压缩延迟（ms）',description:'消息写入后至少等待多久才允许参与日志压缩。',numeric:true},
  {field:'maxCompactionLagMs',name:'max.compaction.lag.ms',label:'最大压缩延迟（ms）',description:'消息在满足条件后等待压缩的最长时间。',numeric:true},
  {field:'messageTimestampType',name:'message.timestamp.type',label:'消息时间类型',description:'CreateTime 使用生产者时间；LogAppendTime 使用 Broker 写入时间。',options:['CreateTime','LogAppendTime']},
] as const;

function TopicConfigPanel({topic,canManage}:{topic:string;canManage:boolean}) {
  const {toast}=useFeedback();
  const [draft,setDraft]=useState<Record<string,string>>({});
  const config=useQuery<TopicConfig>({queryKey:['kafka','topic-config',topic],queryFn:async()=>(await api.get(`/kafka/topics/${encodeURIComponent(topic)}/config`)).data,retry:false});
  const update=useMutation({mutationFn:async()=>{const body=Object.fromEntries(EDITABLE_TOPIC_CONFIGS.flatMap(item=>{const value=draft[item.field];return value==null||value===''?[]:[[item.field,'numeric' in item&&item.numeric?Number(value):value]];}));return api.patch(`/kafka/topics/${encodeURIComponent(topic)}/config`,body);},onSuccess:()=>{setDraft({});toast('Topic 配置已更新',{tone:'success'});void config.refetch();},onError:(e:any)=>toast(e?.response?.data?.message||e.message,{tone:'error'})});
  const changed=Object.values(draft).some(value=>value!=='');
  return <section className="card p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Topic 配置</h2><p className="mt-1 text-xs text-muted">展示 Broker 返回的当前有效值、配置来源和常用参数说明。</p></div><button className="icon-btn" onClick={()=>config.refetch()} aria-label="刷新 Topic 配置"><RefreshCw size={14}/></button></div>{config.error&&<p className="mt-3 text-xs text-red-500">Topic 配置读取失败</p>}<div className="mt-4 max-h-72 overflow-auto rounded-xl border dark:border-slate-800"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-muted dark:bg-slate-900"><tr><th className="p-2">配置项</th><th>当前值</th><th>来源</th><th>说明</th></tr></thead><tbody>{config.data?.entries.map(entry=>{const definition=EDITABLE_TOPIC_CONFIGS.find(item=>item.name===entry.name);return <tr key={entry.name} className="border-t align-top dark:border-slate-800"><td className="p-2 font-mono">{entry.name}</td><td className="max-w-72 break-all py-2 pr-3 font-mono">{entry.sensitive?'••••••':entry.value??'—'}</td><td className="py-2 pr-2">{entry.readOnly?'只读':entry.isDefault?'默认值':'Topic 覆盖'}</td><td className="max-w-80 py-2 pr-2 text-muted">{definition?.description??'Kafka 原生配置，当前仅展示，不支持在此页面修改。'}</td></tr>})}</tbody></table></div>{canManage&&<details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">修改常用配置</summary><p className="mt-2 text-xs text-amber-600 dark:text-amber-400">只填写需要变更的项目；提交后立即作用于当前 Topic，请先确认副本和生产者配置是否兼容。</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{EDITABLE_TOPIC_CONFIGS.map(item=>{const current=config.data?.entries.find(entry=>entry.name===item.name)?.value??'';return <label key={item.field} className="text-xs"><span className="mb-1 block font-semibold">{item.label}</span><span className="mb-2 block min-h-8 text-[10px] leading-4 text-muted">{item.description}</span>{'options' in item?<select className="input w-full" value={draft[item.field]??''} onChange={event=>setDraft(value=>({...value,[item.field]:event.target.value}))}><option value="">当前：{current||'未设置'}</option>{item.options.map(option=><option key={option} value={option}>{option}</option>)}</select>:<input className="input w-full" type="number" placeholder={current||'未设置'} value={draft[item.field]??''} onChange={event=>setDraft(value=>({...value,[item.field]:event.target.value}))}/>}</label>;})}</div><div className="mt-4 flex justify-end"><button className="btn btn-primary" disabled={!changed||update.isPending} onClick={()=>update.mutate()}>{update.isPending?'保存中…':'保存配置'}</button></div></details>}</section>;
}

function ConsumerDetails({consumers}:{consumers:Consumer[]}) {
  if (!consumers.length) return <div className="mt-3 rounded-lg bg-slate-50 px-3 py-2 text-muted dark:bg-slate-900">当前没有在线消费者</div>;
  return <details className="mt-3" open={consumers.length<=3}><summary className="cursor-pointer font-semibold text-muted">消费者工作状态</summary><div className="mt-2 max-h-64 space-y-2 overflow-auto">{consumers.map(consumer=><div key={consumer.memberId} className="rounded-lg bg-slate-50 p-3 dark:bg-slate-900"><div className="flex items-center justify-between gap-2"><span className="truncate font-semibold" title={consumer.memberId}>{consumer.clientId||consumer.memberId}</span><ConsumerStatus status={consumer.status}/></div><div className="mt-1 text-[10px] text-muted">{consumer.clientHost||'未知地址'} · {consumer.partitionCount} 个分区</div><div className="mt-2 space-y-1">{consumer.assignment.map(item=><div key={item.topic} className="break-all"><span className="text-muted">{item.topic}</span>：{item.partitions.join(', ')||'未分配'}</div>)}</div></div>)}</div></details>;
}

function ConsumerStatus({status}:{status:Consumer['status']}) {
  const labels={working:'工作中',idle:'空闲',rebalancing:'重平衡中'} as const;
  const tones={working:'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10',idle:'bg-slate-100 text-slate-500 dark:bg-slate-800',rebalancing:'bg-amber-50 text-amber-600 dark:bg-amber-500/10'} as const;
  return <span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-bold ${tones[status]}`}>{labels[status]}</span>;
}
