import { useEffect, useState } from "react";
import { OrganizationInvitation } from '../Settings/OrganizationInvitation';
import { CheckCircle2, Download, FileKey2, KeyRound, Laptop, LoaderCircle, LogIn, LogOut, RefreshCw, Server, ShieldCheck, Trash2, Upload, UserRound } from "lucide-react";

interface AccountState { serverUrl: string | null; signedIn: boolean; user: { id: string; username: string } | null; deviceId: string; license: { state: string; edition: string; expiresAt?: string | null; graceUntil?: string | null }; policy: { state: string; expiresAt?: string | null; offlineUntil?: string | null; organizationId?: string | null } }
interface Device { id: string; deviceId: string; name?: string; platform?: string; appVersion?: string; lastSeenAt?: string; revokedAt?: string | null }

export function DesktopAccount() {
  const [account, setAccount] = useState<AccountState>(); const [devices, setDevices] = useState<Device[]>([]);
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const [redeemCode, setRedeemCode] = useState("");
  useEffect(() => { void load(); }, []);
  async function load() {
    setError(""); try { const response = await fetch("/api/local/account"); const body = await response.json(); if (!response.ok) throw new Error(body.message || `HTTP ${response.status}`); setAccount(body); if (body.signedIn) await loadDevices(); else setDevices([]); } catch (reason: any) { setError(String(reason?.message || reason)); }
  }
  async function loadDevices() { const response = await fetch("/api/local/account/devices"); const body = await response.json(); if (response.ok) setDevices(body.items || []); }
  async function login() { setBusy("login"); setError(""); try { const response = await fetch("/api/local/account/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || `HTTP ${response.status}`); setPassword(""); await load(); } catch (reason: any) { setError(String(reason?.message || reason)); } finally { setBusy(""); } }
  async function activate() { setBusy("activate"); setError(""); try { const response = await fetch("/api/local/account/license/activate", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.message || `HTTP ${response.status}`); await load(); } catch (reason: any) { setError(String(reason?.message || reason)); } finally { setBusy(""); } }
  async function redeem() { setBusy("redeem"); setError(""); try { const response = await fetch("/api/local/account/license/redeem", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code: redeemCode }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || `HTTP ${response.status}`); setRedeemCode(""); const activation = await fetch("/api/local/account/license/activate", { method: "POST" }); const activationBody = await activation.json(); if (!activation.ok) throw new Error(activationBody.message || `HTTP ${activation.status}`); await load(); } catch (reason: any) { setError(String(reason?.message || reason)); } finally { setBusy(""); } }
  async function logout() { setBusy("logout"); await fetch("/api/local/account", { method: "DELETE" }); await load(); setBusy(""); }
  async function revoke(id: string) { if (!window.confirm("撤销这台设备的许可证吗？该设备下次联网后需要重新激活。")) return; setBusy(id); const response = await fetch(`/api/local/account/devices/${id}`, { method: "DELETE" }); const body = await response.json(); if (!response.ok) setError(body.message || `HTTP ${response.status}`); else await loadDevices(); setBusy(""); }
  async function exportOffline() { setBusy("offline-export"); setError(""); try { const result = await window.desktopRuntime?.exportLicenseChallenge(); if (result?.message) throw new Error(result.message); } catch (reason: any) { setError(String(reason?.message || reason)); } finally { setBusy(""); } }
  async function importOffline() { setBusy("offline-import"); setError(""); try { const result = await window.desktopRuntime?.importLicenseFile(); if (result?.message) throw new Error(result.message); if (result?.ok) await load(); } catch (reason: any) { setError(String(reason?.message || reason)); } finally { setBusy(""); } }
  async function refreshPolicy() { setBusy("policy"); setError(""); try { const response = await fetch("/api/local/account/enterprise/policy/refresh", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.message || `HTTP ${response.status}`); await load(); } catch (reason: any) { setError(String(reason?.message || reason)); } finally { setBusy(""); } }
  const licensed = account && ["active", "grace"].includes(account.license.state);
  const invitationSection = account?.signedIn ? <div className="mt-4"><OrganizationInvitation desktop /></div> : null;
  return <div className="h-full overflow-auto rounded-[22px] border border-white/80 bg-white/40 p-6 shadow-sm backdrop-blur-sm dark:border-slate-800/80 dark:bg-slate-950/25"><div className="mx-auto max-w-4xl"><div className="eyebrow">Account</div><h1 className="mt-1 text-2xl font-bold">账户与许可证</h1><p className="mt-1 text-sm text-muted">不登录也能使用全部本地核心功能；登录仅用于订阅、同步和团队能力。</p>
    <section className="card mt-6 p-5"><div className="flex items-start gap-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10 dark:text-indigo-300"><Server size={19} /></span><div className="min-w-0 flex-1"><h2 className="text-sm font-bold">服务连接</h2><p className="mt-1 truncate text-xs text-muted">{account?.serverUrl || "尚未配置团队或个人订阅服务"}</p></div><button className="btn btn-ghost btn-sm" onClick={() => void window.desktopRuntime?.configureControlServer()}><Server size={13} />配置</button><button className="icon-btn" title="刷新" onClick={() => void load()}><RefreshCw size={14} /></button></div></section>
    {!account?.signedIn ? <section className="card mt-4 p-5"><h2 className="flex items-center gap-2 text-sm font-bold"><LogIn size={16} />登录</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input className="input" value={username} onChange={(event) => setUsername(event.target.value)} placeholder="用户名或邮箱" autoComplete="username" /><input className="input" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="密码" autoComplete="current-password" /></div><button className="btn btn-primary mt-3" disabled={!account?.serverUrl || !username.trim() || !password || Boolean(busy)} onClick={() => void login()}>{busy === "login" ? <LoaderCircle size={14} className="animate-spin" /> : <LogIn size={14} />}登录账号</button></section> : <>
      <section className="card mt-4 p-5"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><UserRound size={19} /></span><div className="min-w-0 flex-1"><h2 className="text-sm font-bold">{account.user?.username}</h2><p className="mt-1 text-xs text-muted">已安全连接，登录凭据仅加密保存在当前设备。</p></div><button className="btn btn-ghost btn-sm" disabled={Boolean(busy)} onClick={() => void logout()}><LogOut size={13} />退出登录</button></div></section>
      <section className="card mt-4 p-5"><div className="flex items-center gap-4"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${licensed ? "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10" : "bg-amber-50 text-amber-600 dark:bg-amber-500/10"}`}>{licensed ? <CheckCircle2 size={19} /> : <KeyRound size={19} />}</span><div className="min-w-0 flex-1"><h2 className="text-sm font-bold">{licensed ? editionLabel(account.license.edition) : "Community"}</h2><p className="mt-1 text-xs text-muted">{licensed ? `有效至 ${new Date(account.license.expiresAt || "").toLocaleString()}` : "本地项目、代码、Git、终端和本地 Agent 永久可用"}</p></div><button className="btn btn-primary btn-sm" disabled={busy === "activate"} onClick={() => void activate()}>{busy === "activate" ? <LoaderCircle size={13} className="animate-spin" /> : <KeyRound size={13} />}{licensed ? "刷新许可证" : "激活此设备"}</button></div><div className="mt-4 flex gap-2 border-t border-slate-200 pt-4 dark:border-slate-800"><input className="input min-w-0 flex-1 font-mono uppercase" value={redeemCode} onChange={(event) => setRedeemCode(event.target.value)} placeholder="输入兑换码" autoComplete="off" spellCheck={false} /><button className="btn btn-ghost" disabled={redeemCode.trim().length < 12 || busy === "redeem"} onClick={() => void redeem()}>{busy === "redeem" ? <LoaderCircle size={13} className="animate-spin" /> : <KeyRound size={13} />}兑换并激活</button></div></section>
      <section className="card mt-4 p-5"><h2 className="flex items-center gap-2 text-sm font-bold"><Laptop size={16} />已激活设备</h2><div className="mt-3 space-y-2">{devices.filter((item) => !item.revokedAt).map((device) => <div key={device.id} className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-2.5 dark:border-slate-700"><Laptop size={15} className="text-slate-400" /><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{device.name || device.platform || "设备"}{device.deviceId === account.deviceId ? " · 当前设备" : ""}</div><div className="mt-0.5 text-[10px] text-muted">{[device.platform, device.appVersion].filter(Boolean).join(" · ") || "客户端信息未上报"}</div></div><button className="icon-btn text-red-500" disabled={busy === device.id} title="撤销" onClick={() => void revoke(device.id)}>{busy === device.id ? <LoaderCircle size={13} className="animate-spin" /> : <Trash2 size={13} />}</button></div>)}{!devices.some((item) => !item.revokedAt) && <p className="text-xs text-muted">尚未激活任何设备。</p>}</div></section>
      {account.license.edition === "enterprise" && <section className="card mt-4 p-5"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-sky-50 text-sky-600 dark:bg-sky-500/10"><ShieldCheck size={19} /></span><div className="min-w-0 flex-1"><h2 className="text-sm font-bold">企业安全策略</h2><p className={`mt-1 text-xs ${account.policy?.state === "upgrade-required" ? "text-amber-600" : "text-muted"}`}>{["active", "grace"].includes(account.policy?.state) ? `已应用 · 离线可用至 ${new Date(account.policy.offlineUntil || "").toLocaleString()}` : account.policy?.state === "upgrade-required" ? "当前客户端版本低于企业要求，请升级后刷新策略" : "尚未获取企业策略"}</p></div><button className="btn btn-ghost btn-sm" disabled={Boolean(busy)} onClick={() => void refreshPolicy()}>{busy === "policy" ? <LoaderCircle size={13} className="animate-spin" /> : <RefreshCw size={13} />}刷新策略</button></div></section>}
    </>}
    <section className="card mt-4 p-5"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-violet-50 text-violet-600 dark:bg-violet-500/10 dark:text-violet-300"><FileKey2 size={19} /></span><div className="min-w-0 flex-1"><h2 className="text-sm font-bold">离线许可证</h2><p className="mt-1 text-xs leading-5 text-muted">无法联网时，先导出设备申请文件，由许可证管理员签发后再导入。许可证与当前设备绑定。</p><div className="mt-3 flex flex-wrap gap-2"><button className="btn btn-ghost btn-sm" disabled={Boolean(busy)} onClick={() => void exportOffline()}>{busy === "offline-export" ? <LoaderCircle size={13} className="animate-spin" /> : <Download size={13} />}导出离线申请</button><button className="btn btn-primary btn-sm" disabled={Boolean(busy)} onClick={() => void importOffline()}>{busy === "offline-import" ? <LoaderCircle size={13} className="animate-spin" /> : <Upload size={13} />}导入许可证</button></div></div></div></section>
    {invitationSection}
    {error && <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-600 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300">{error}</div>}
  </div></div>;
}

function editionLabel(edition: string) { return ({ "personal-pro": "Personal Pro", team: "Team", enterprise: "Enterprise" } as Record<string, string>)[edition] || edition; }
