CREATE TABLE "KnowledgeFolder" ("id" TEXT NOT NULL,"teamId" TEXT NOT NULL,"parentId" TEXT,"name" TEXT NOT NULL,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "KnowledgeFolder_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KnowledgeDocument" ("id" TEXT NOT NULL,"teamId" TEXT NOT NULL,"folderId" TEXT,"requirementId" TEXT,"title" TEXT NOT NULL,"contentMarkdown" TEXT NOT NULL DEFAULT '',"layoutJson" JSONB,"version" INTEGER NOT NULL DEFAULT 1,"createdById" TEXT NOT NULL,"updatedById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "KnowledgeDocument_pkey" PRIMARY KEY ("id"));
CREATE TABLE "KnowledgeDocumentRevision" ("id" TEXT NOT NULL,"documentId" TEXT NOT NULL,"version" INTEGER NOT NULL,"contentMarkdown" TEXT NOT NULL,"layoutJson" JSONB,"changeSummary" TEXT,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "KnowledgeDocumentRevision_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "KnowledgeFolder_teamId_parentId_name_key" ON "KnowledgeFolder"("teamId","parentId","name");
CREATE INDEX "KnowledgeFolder_teamId_parentId_idx" ON "KnowledgeFolder"("teamId","parentId");
CREATE UNIQUE INDEX "KnowledgeDocument_requirementId_key" ON "KnowledgeDocument"("requirementId");
CREATE INDEX "KnowledgeDocument_teamId_folderId_updatedAt_idx" ON "KnowledgeDocument"("teamId","folderId","updatedAt");
CREATE UNIQUE INDEX "KnowledgeDocumentRevision_documentId_version_key" ON "KnowledgeDocumentRevision"("documentId","version");
CREATE INDEX "KnowledgeDocumentRevision_documentId_createdAt_idx" ON "KnowledgeDocumentRevision"("documentId","createdAt");
ALTER TABLE "KnowledgeFolder" ADD CONSTRAINT "KnowledgeFolder_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE;
ALTER TABLE "KnowledgeFolder" ADD CONSTRAINT "KnowledgeFolder_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "KnowledgeFolder"("id") ON DELETE RESTRICT;
ALTER TABLE "KnowledgeFolder" ADD CONSTRAINT "KnowledgeFolder_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT;
ALTER TABLE "KnowledgeDocument" ADD CONSTRAINT "KnowledgeDocument_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE;
ALTER TABLE "KnowledgeDocument" ADD CONSTRAINT "KnowledgeDocument_folderId_fkey" FOREIGN KEY ("folderId") REFERENCES "KnowledgeFolder"("id") ON DELETE RESTRICT;
ALTER TABLE "KnowledgeDocument" ADD CONSTRAINT "KnowledgeDocument_requirementId_fkey" FOREIGN KEY ("requirementId") REFERENCES "Requirement"("id") ON DELETE SET NULL;
ALTER TABLE "KnowledgeDocument" ADD CONSTRAINT "KnowledgeDocument_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT;
ALTER TABLE "KnowledgeDocument" ADD CONSTRAINT "KnowledgeDocument_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE RESTRICT;
ALTER TABLE "KnowledgeDocumentRevision" ADD CONSTRAINT "KnowledgeDocumentRevision_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "KnowledgeDocument"("id") ON DELETE CASCADE;
ALTER TABLE "KnowledgeDocumentRevision" ADD CONSTRAINT "KnowledgeDocumentRevision_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT;
