import { useEffect, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Boxes, Cpu, MemoryStick, Network, RefreshCw, RotateCcw } from 'lucide-react';
import { api } from '../../lib/api';
import { Select } from '../common/Select';
import { InteractiveLineChart } from './InteractiveLineChart';
import { useDeployTargets } from '../../hooks/useDeploy';
import { useSearchParams } from 'react-router-dom';

type Metric = { current: number | null; points: Array<{ timestamp: string; value: number }> };
type PodMetric = { namespace: string; podName: string; cpu?: Metric; memory?: Metric; networkReceive?: Metric; networkTransmit?: Metric; restarts?: Metric; ready?: Metric };
type PodResponse = { sourceAvailable: boolean; pods: PodMetric[]; stepSeconds: number };

export function PodMonitoringPage() {
  const [searchParams] = useSearchParams();
  const { data: deployTargets = [] } = useDeployTargets('deploy');
  const kubernetesTargets = deployTargets.filter((target) => target.kind === 'k8s' && target.enabled);
  const [targetId, setTargetId] = useState(() => searchParams.get('targetId') || ''); const [namespace, setNamespace] = useState(() => searchParams.get('namespace') || ''); const [podFilter, setPodFilter] = useState(''); const [podPrefix] = useState(() => searchParams.get('podPrefix') || ''); const [minutes, setMinutes] = useState('60'); const [selected, setSelected] = useState('');
  useEffect(() => { if (!targetId && kubernetesTargets.length) setTargetId(kubernetesTargets[0].id); }, [targetId, kubernetesTargets]);
  const namespaces = useQuery<{ targetId: string; targetName: string; namespaces: string[] }>({ queryKey: ['metric-namespaces', targetId], enabled: !!targetId, queryFn: async () => (await api.get('/resource-metrics/kubernetes/namespaces', { params: { targetId } })).data, refetchInterval: 30_000, retry: false });
  useEffect(() => { if (!namespace && namespaces.data?.namespaces.length) setNamespace(namespaces.data.namespaces[0]); }, [namespace, namespaces.data]);
  const query = useQuery<PodResponse>({ queryKey: ['pod-metrics', targetId, namespace, podFilter, podPrefix, minutes], enabled: !!targetId, queryFn: async () => (await api.get('/resource-metrics/kubernetes/pods', { params: { targetId, namespace: namespace || undefined, pod: podFilter || undefined, podPrefix: podFilter ? undefined : podPrefix || undefined, minutes } })).data, refetchInterval: 30_000, retry: false });
  useEffect(() => { if (selected && !query.data?.pods.some((pod) => pod.podName === selected)) setSelected(''); }, [selected, query.data]);
  const selectedPod = query.data?.pods.find((pod) => pod.podName === selected);
  const summary = useMemo(() => ({ pods: query.data?.pods.length ?? 0, ready: query.data?.pods.filter((pod) => pod.ready && (pod.ready.current ?? 0) >= 1).length ?? 0, readyKnown: query.data?.pods.some((pod) => !!pod.ready) ?? false, cpu: query.data?.pods.reduce((sum, pod) => sum + (pod.cpu?.current ?? 0), 0) ?? 0, memory: query.data?.pods.reduce((sum, pod) => sum + (pod.memory?.current ?? 0), 0) ?? 0 }), [query.data]);
  return <div className="h-full overflow-y-auto rounded-[22px] border border-white/80 bg-white/45 dark:border-slate-800/80 dark:bg-slate-950/25"><div className="page-shell max-w-[1600px]">
    <header className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Kubernetes Workloads</div><h1 className="mt-1 text-2xl font-bold">Pod 监控</h1><p className="mt-1 text-sm text-muted">查看业务实际部署目标集群中的 Pod 资源</p><p className="mt-1 text-[10px] text-emerald-600">目标集群内新增 Namespace/Pod 会自动出现，无需为 Pod 修改配置</p></div><div className="flex flex-wrap items-end gap-2"><Filter label="部署目标"><Select value={targetId} onChange={(value) => { setTargetId(value); setNamespace(''); setSelected(''); }} options={kubernetesTargets.map((target) => ({value:target.id,label:target.name}))} placeholder="选择 Kubernetes 目标" /></Filter><Filter label="Namespace"><Select value={namespace} onChange={(value) => { setNamespace(value); setSelected(''); }} options={[{value:'',label:'全部 Namespace'},...(namespaces.data?.namespaces ?? []).map((value) => ({value,label:value}))]} /></Filter><Filter label="Pod 精确名称"><input className="input h-10 w-48" value={podFilter} onChange={(event) => setPodFilter(event.target.value)} placeholder="可选" /></Filter><Filter label="时间范围"><Select value={minutes} onChange={setMinutes} options={[{value:'15',label:'15 分钟'},{value:'60',label:'1 小时'},{value:'360',label:'6 小时'},{value:'1440',label:'24 小时'}]} /></Filter><button className="btn btn-primary h-10" disabled={!targetId} onClick={() => { namespaces.refetch(); query.refetch(); }}><RefreshCw size={14} className={query.isFetching || namespaces.isFetching ? 'animate-spin' : ''}/>刷新</button></div></header>
    {!kubernetesTargets.length && <div className="card mt-4 p-8 text-center"><Boxes className="mx-auto text-slate-300" size={34}/><div className="mt-3 font-bold">请先创建 Kubernetes 部署目标</div><p className="mt-2 text-xs text-muted">在“设置 → 运行资源”中添加目标集群，并配置该集群的 Prometheus 地址。</p></div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Boxes size={17}/>} label="Pod 总数" value={String(summary.pods)} hint={summary.readyKnown ? `${summary.ready} Ready` : "Ready 数据待接入"} /><Stat icon={<Cpu size={17}/>} label="CPU 合计" value={`${summary.cpu.toFixed(3)} 核`} hint="所选 Pod 当前使用" /><Stat icon={<MemoryStick size={17}/>} label="内存合计" value={bytes(summary.memory)} hint="工作集内存" /><Stat icon={<RotateCcw size={17}/>} label="重启次数" value={query.data?.pods.some((pod)=>!!pod.restarts)?String(query.data.pods.reduce((sum,pod)=>sum+(pod.restarts?.current??0),0)):"—"} hint="kube-state-metrics 累计值" /></div>
    {query.error && <div className="card mt-4 border-amber-200 p-4 text-xs text-amber-700">Pod 指标查询失败：{(query.error as any)?.response?.data?.message || String(query.error)}</div>}
    {!!targetId && !query.isLoading && !query.error && !query.data?.sourceAvailable && <div className="card mt-4 p-8 text-center"><Boxes className="mx-auto text-slate-300" size={34}/><div className="mt-3 font-bold">目标集群暂时没有 Pod 指标</div><p className="mx-auto mt-2 max-w-2xl text-xs text-muted">请确认该部署目标的 Prometheus 已采集 kubelet/cAdvisor 和 kube-state-metrics。接入一次后，后续新 Pod 会自动发现。</p></div>}
    {!!query.data?.pods.length && <div className="mt-4 grid gap-4 xl:grid-cols-[460px_1fr]"><section className="card overflow-hidden"><div className="border-b p-4 text-sm font-bold dark:border-slate-800">Pod 列表</div><div className="max-h-[650px] overflow-auto"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-muted dark:bg-slate-900"><tr><th className="px-4 py-3">Pod</th><th>状态</th><th>CPU</th><th>内存</th></tr></thead><tbody>{query.data.pods.map((pod) => <tr key={`${pod.namespace}/${pod.podName}`} onClick={() => setSelected(pod.podName)} className={`cursor-pointer border-t dark:border-slate-800 ${selected === pod.podName ? 'bg-indigo-50 dark:bg-indigo-500/10' : 'hover:bg-slate-50 dark:hover:bg-slate-900'}`}><td className="max-w-56 truncate px-4 py-3"><b title={pod.podName}>{pod.podName}</b><div className="mt-1 text-[9px] text-muted">{pod.namespace}</div></td><td><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${(pod.ready?.current??0)>=1?'bg-emerald-50 text-emerald-600':'bg-red-50 text-red-600'}`}>{(pod.ready?.current??0)>=1?'Ready':'Not Ready'}</span></td><td>{(pod.cpu?.current??0).toFixed(3)}</td><td>{bytes(pod.memory?.current??0)}</td></tr>)}</tbody></table></div></section><section className="card p-5">{selectedPod ? <PodCharts pod={selectedPod}/> : <div className="grid h-full min-h-96 place-items-center text-sm text-muted">点击左侧 Pod 查看交互趋势图</div>}</section></div>}
  </div></div>;
}
function PodCharts({ pod }: { pod: PodMetric }) { const charts = [{title:'CPU 使用',metric:pod.cpu,unit:'cores',color:'#6366f1'},{title:'工作集内存',metric:pod.memory,unit:'bytes',color:'#10b981'},{title:'网络接收',metric:pod.networkReceive,unit:'bytes/s',color:'#0ea5e9'},{title:'网络发送',metric:pod.networkTransmit,unit:'bytes/s',color:'#f59e0b'}]; return <><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{pod.podName}</h2><p className="mt-1 text-xs text-muted">{pod.namespace}</p></div><div className="flex gap-2 text-[10px]"><span className="rounded-full bg-slate-100 px-2.5 py-1 dark:bg-slate-800">重启 {pod.restarts?.current??0}</span><span className={`rounded-full px-2.5 py-1 ${(pod.ready?.current??0)>=1?'bg-emerald-50 text-emerald-600':'bg-red-50 text-red-600'}`}>{(pod.ready?.current??0)>=1?'Ready':'Not Ready'}</span></div></div><div className="mt-5 grid gap-5 2xl:grid-cols-2">{charts.map((chart) => <div key={chart.title} className="rounded-xl border p-3 dark:border-slate-800"><div className="mb-2 flex items-center gap-2 text-xs font-bold"><Network size={13}/>{chart.title}</div><InteractiveLineChart height={230} series={[{name:chart.title,points:chart.metric?.points??[],color:chart.color,unit:chart.unit}]}/></div>)}</div></>; }
function Filter({label,children}:{label:string;children:React.ReactNode}) { return <label className="text-xs text-muted"><span className="mb-1 block">{label}</span>{children}</label>; }
function Stat({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint:string}) { return <div className="card p-4"><span className="grid h-8 w-8 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10">{icon}</span><div className="mt-3 text-xs text-muted">{label}</div><div className="mt-1 text-2xl font-bold">{value}</div><div className="mt-1 text-[10px] text-muted">{hint}</div></div>; }
function bytes(value:number) { if(value>=1024**3)return `${(value/1024**3).toFixed(2)} GiB`;if(value>=1024**2)return `${(value/1024**2).toFixed(1)} MiB`;return `${(value/1024).toFixed(1)} KiB`; }
