const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const { LocalStore } = require('../src/local-store.cjs');

test('SQLite store migrates and persists projects and settings across restarts', (t) => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'code-studio-store-'));
  const databasePath = path.join(directory, 'local.sqlite3');
  t.after(() => fs.rmSync(directory, { recursive: true, force: true }));
  let store = new LocalStore(databasePath);
  assert.equal(store.getSchemaVersion(), 7);
  store.upsertProject({ id: 'project-1', name: 'Demo', path: '/tmp/demo', openedAt: '2026-09-23T01:00:00.000Z' });
  store.setSetting('theme', { value: 'dark' });
  store.setPrivacySetting('settingsSync', true);
  store.upsertModelConfig({ id: 'model-1', name: 'Local Codex', engine: 'codex-cli', provider: 'openai', model: 'gpt-5' }, 'encrypted-secret');
  store.upsertConnector({ id: 'connector-1', name: 'Main DB', type: 'postgres', settings: { host: '127.0.0.1', port: 5432, database: 'app', username: 'app', ssl: false } }, 'encrypted-password');
  store.createAgentTask({ id: 'task-1', projectId: 'project-1', modelConfigId: 'model-1', selectedModel: 'gpt-6-sol', reasoningEffort: 'high', prompt: 'work', permissionProfile: 'workspace-write', status: 'running', createdAt: '2026-09-23T01:01:00.000Z' });
  store.updateAgentTask('task-1', 'running', { inputTokens: 120, cachedInputTokens: 40, outputTokens: 30 });
  store.addAgentEvent('task-1', { kind: 'text', text: 'partial' });
  store.close();
  store = new LocalStore(databasePath);
  assert.deepEqual(store.listProjects(), [{ id: 'project-1', name: 'Demo', path: '/tmp/demo', openedAt: '2026-09-23T01:00:00.000Z' }]);
  assert.deepEqual(store.getSetting('theme'), { value: 'dark' });
  assert.equal(store.getSetting('privacy.settingsSync'), true);
  assert.deepEqual(store.listPrivacyAudit(), [{ key: 'settingsSync', enabled: true, changedAt: store.listPrivacyAudit()[0].changedAt }]);
  assert.equal(store.getModelConfig('model-1').credentialCiphertext, 'encrypted-secret');
  assert.equal(store.listModelConfigs()[0].name, 'Local Codex');
  assert.equal(store.getConnector('connector-1').settings.database, 'app');
  assert.equal(store.listConnectors()[0].credentialCiphertext, 'encrypted-password');
  assert.equal(store.getAgentTask('task-1').status, 'interrupted');
  assert.equal(store.getAgentTask('task-1').permissionProfile, 'workspace-write');
  assert.equal(store.getAgentTask('task-1').selectedModel, 'gpt-6-sol');
  assert.equal(store.getAgentTask('task-1').reasoningEffort, 'high');
  assert.equal(store.getAgentTask('task-1').inputTokens, 120);
  assert.deepEqual(store.listAgentUsage(), [{ model: 'gpt-6-sol', tasks: 1, inputTokens: 120, cachedInputTokens: 40, outputTokens: 30 }]);
  assert.equal(store.getAgentTask('task-1').events[0].text, 'partial');
  store.deleteModelConfig('model-1');
  assert.deepEqual(store.listModelConfigs(), []);
  store.deleteConnector('connector-1'); assert.deepEqual(store.listConnectors(), []);
  store.removeProject('project-1');
  assert.deepEqual(store.listProjects(), []);
  store.close();
});
